// Auto-generated by fetch_tiktoks.py — do not edit manually.
// Last updated: 2026-08-06T05:56:38Z  |  Total TikToks: 84
// Run: python3 fetch_tiktoks.py --count N
window.TIKTOK_DATES  = {
  "2026-01-03": 2,
  "2026-01-01": 3,
  "2026-01-06": 1,
  "2025-12-30": 1,
  "2025-12-31": 1,
  "2026-01-05": 1,
  "2024-11-08": 1,
  "2024-11-20": 1,
  "2023-11-28": 1,
  "2025-12-10": 2,
  "2025-12-04": 3,
  "2025-12-16": 1,
  "2025-12-17": 1,
  "2025-12-19": 2,
  "2025-12-15": 3,
  "2025-12-21": 1,
  "2025-12-14": 6,
  "2025-12-24": 1,
  "2025-12-25": 1,
  "2025-12-05": 1,
  "2025-12-23": 1,
  "2025-12-29": 1,
  "2023-04-16": 1,
  "2023-04-22": 1,
  "2023-05-01": 1,
  "2023-04-21": 1,
  "2025-12-11": 2,
  "2025-12-07": 5,
  "2025-12-13": 1,
  "2025-11-23": 2,
  "2025-11-26": 1,
  "2025-10-17": 1,
  "2025-11-30": 1,
  "2025-11-08": 1,
  "2025-12-03": 2,
  "2025-11-28": 1,
  "2025-10-23": 1,
  "2025-12-01": 1,
  "2025-10-18": 1,
  "2025-10-26": 2,
  "2025-12-09": 2,
  "2025-11-12": 1,
  "2025-11-18": 3,
  "2025-12-12": 1,
  "2025-11-16": 1,
  "2025-11-27": 1,
  "2025-10-10": 1,
  "2025-12-02": 2,
  "2025-11-29": 3,
  "2025-10-30": 1,
  "2025-10-25": 1,
  "2025-10-27": 1,
  "2025-10-16": 1,
  "2025-12-06": 1,
  "2025-11-22": 1,
  "2025-10-13": 1
};
window.TIKTOK_VIDEOS = {
  "2026-01-03": [
    {
      "id": "tt_7591098857786805506",
      "text": "03.01 | #moodboard #lifestyle #fyp #itboy #cleanboy ",
      "author_name": "⃟",
      "author_handle": "@cleanlifeguides",
      "created_at": "2026-01-03T11:40:43Z",
      "url": "https://www.tiktok.com/@cleanlifeguides/video/7591098857786805506",
      "like_count": 19700,
      "bookmark_count": "2944",
      "comment_count": 31,
      "share_count": 1173,
      "view_count": 105800,
      "images": [
        {
          "url": "media/tiktok/7591098857786805506/7591098857786805506_thumb.jpg",
          "type": "video",
          "video_url": "media/tiktok/7591098857786805506/7591098857786805506.mp4"
        }
      ],
      "duration": 14
    },
    {
      "id": "tt_7591289647020494102",
      "text": "Tigers symbolize strength, courage, and confidence in many cultures around the world. Flowers often rpresent beauty, growth, and the gentle side of nature. When thinking about tigers and flowers together, they show how nature can be both powerful and soft at the same time. The tigers beauty comes from its bold stripes and fearless presence. The beuauty of flowers comes from their colors, shapes, and calming efect. Both remind us that beauty is not only about appearance, but also meaning and feeling. together, tigers and flowers teach us to respect nature in all its forms. #tiger #moodboard #culture #art #flowers ",
      "author_name": "m",
      "author_handle": "@jcezxv",
      "created_at": "2026-01-04T00:01:04Z",
      "url": "https://www.tiktok.com/@jcezxv/video/7591289647020494102",
      "like_count": 794300,
      "bookmark_count": "110241",
      "comment_count": 1359,
      "share_count": 37700,
      "view_count": 3500000,
      "images": [
        {
          "url": "media/tiktok/7591289647020494102/7591289647020494102_thumb.jpg",
          "type": "video",
          "video_url": "media/tiktok/7591289647020494102/7591289647020494102.mp4"
        }
      ],
      "duration": 11
    }
  ],
  "2026-01-01": [
    {
      "id": "tt_7590530715016645919",
      "text": "No, you’re not messed up—you literally can’t help but be drawn to him.  The tortured pretty-boy aesthetic in media and fashion is a fascinating glimpse into how biology, psychology, societal pressures, media influence and the state of the world impact how we dress, express ourselves and influence what we are drawn to at a given time.  His dichotomous nature—soft yet tough, vulnerable yet defiant—makes him irresistible on every level: visual, emotional, psychological. But what makes him truly hit is his embodiment of a deeply rooted desire: to be authentic without punishment, to feel and display pain without shame (especially among men).  His influence runs deep and wide—even influencing dating culture and beauty trends. But more than that, it underscores the power of marketing and how certain images, style choices and aesthetics can influence mainstream trends and consumer behavior. . . #fashionhistory #fashionhistorian #anakinedit ",
      "author_name": "Trends of the Times",
      "author_handle": "@trendsofthetimes",
      "created_at": "2026-01-01T22:56:16Z",
      "url": "https://www.tiktok.com/@trendsofthetimes/photo/7590530715016645919",
      "like_count": 67200,
      "bookmark_count": "16452",
      "comment_count": 427,
      "share_count": 3418,
      "view_count": 449100,
      "images": [
        {
          "url": "media/tiktok/7590530715016645919/7590530715016645919_01.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7590530715016645919/7590530715016645919_02.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7590530715016645919/7590530715016645919_03.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7590530715016645919/7590530715016645919_04.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7590530715016645919/7590530715016645919_05.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7590530715016645919/7590530715016645919_06.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7590530715016645919/7590530715016645919_07.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7590530715016645919/7590530715016645919_08.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7590530715016645919/7590530715016645919_09.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7590530715016645919/7590530715016645919_10.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7590530715016645919/7590530715016645919_11.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7590530715016645919/7590530715016645919_12.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7590530715016645919/7590530715016645919_13.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7590530715016645919/7590530715016645919_14.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7590530715016645919/7590530715016645919_15.jpg",
          "type": "photo"
        }
      ],
      "audio_url": "media/tiktok/7590530715016645919/7590530715016645919.mp3"
    },
    {
      "id": "tt_7590534882116390175",
      "text": "#coruscant #starwars #jazz #nostalgia #aesthetic ",
      "author_name": "☾",
      "author_handle": "@izvkul",
      "created_at": "2026-01-01T23:12:27Z",
      "url": "https://www.tiktok.com/@izvkul/video/7590534882116390175",
      "like_count": 472100,
      "bookmark_count": "69594",
      "comment_count": 719,
      "share_count": 40300,
      "view_count": 2500000,
      "images": [
        {
          "url": "media/tiktok/7590534882116390175/7590534882116390175_thumb.jpg",
          "type": "video",
          "video_url": "media/tiktok/7590534882116390175/7590534882116390175.mp4"
        }
      ],
      "duration": 8
    },
    {
      "id": "tt_7590443311136050446",
      "text": "The real story of Marty Supreme 🏓 #martysupreme #timotheechalamet #tabletennis ",
      "author_name": "Frank Michael Smith",
      "author_handle": "@frankmichaelsmith",
      "created_at": "2026-01-01T17:17:16Z",
      "url": "https://www.tiktok.com/@frankmichaelsmith/video/7590443311136050446",
      "like_count": 561500,
      "bookmark_count": "32921",
      "comment_count": 626,
      "share_count": 36300,
      "view_count": 5800000,
      "images": [
        {
          "url": "media/tiktok/7590443311136050446/7590443311136050446_thumb.jpg",
          "type": "video",
          "video_url": "media/tiktok/7590443311136050446/7590443311136050446.mp4"
        }
      ],
      "duration": 69
    }
  ],
  "2026-01-06": [
    {
      "id": "tt_7592269291135831309",
      "text": "TikTok video #7592269291135831309",
      "author_name": "Gabriel",
      "author_handle": "@blessedbythepriest",
      "created_at": "2026-01-06T15:23:30Z",
      "url": "https://www.tiktok.com/@blessedbythepriest/video/7592269291135831309",
      "like_count": 374100,
      "bookmark_count": "37829",
      "comment_count": 571,
      "share_count": 14900,
      "view_count": 2700000,
      "images": [
        {
          "url": "media/tiktok/7592269291135831309/7592269291135831309_thumb.jpg",
          "type": "video",
          "video_url": "media/tiktok/7592269291135831309/7592269291135831309.mp4"
        }
      ],
      "duration": 7
    }
  ],
  "2025-12-30": [
    {
      "id": "tt_7589671680021105942",
      "text": "#outfitinspo #fashiontiktok ",
      "author_name": "Adriano",
      "author_handle": "@adrianoromanini_",
      "created_at": "2025-12-30T15:22:28Z",
      "url": "https://www.tiktok.com/@adrianoromanini_/photo/7589671680021105942",
      "like_count": 60800,
      "bookmark_count": "10747",
      "comment_count": 78,
      "share_count": 2614,
      "view_count": 396200,
      "images": [
        {
          "url": "media/tiktok/7589671680021105942/7589671680021105942_01.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7589671680021105942/7589671680021105942_02.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7589671680021105942/7589671680021105942_03.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7589671680021105942/7589671680021105942_04.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7589671680021105942/7589671680021105942_05.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7589671680021105942/7589671680021105942_06.jpg",
          "type": "photo"
        }
      ],
      "audio_url": "media/tiktok/7589671680021105942/7589671680021105942.mp3"
    }
  ],
  "2025-12-31": [
    {
      "id": "tt_7590112479250812191",
      "text": "Many of these pieces are from our website in bio! #outfitinspo #mensfashion #fashion #outfitideasforyou #90s ",
      "author_name": "archivemainline",
      "author_handle": "@archivemainline",
      "created_at": "2025-12-31T19:53:15Z",
      "url": "https://www.tiktok.com/@archivemainline/photo/7590112479250812191",
      "like_count": 12600,
      "bookmark_count": "2975",
      "comment_count": 11,
      "share_count": 368,
      "view_count": 116300,
      "images": [
        {
          "url": "media/tiktok/7590112479250812191/7590112479250812191_01.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7590112479250812191/7590112479250812191_02.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7590112479250812191/7590112479250812191_03.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7590112479250812191/7590112479250812191_04.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7590112479250812191/7590112479250812191_05.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7590112479250812191/7590112479250812191_06.jpg",
          "type": "photo"
        }
      ],
      "audio_url": "media/tiktok/7590112479250812191/7590112479250812191.mp3"
    }
  ],
  "2026-01-05": [
    {
      "id": "tt_7591989050286804246",
      "text": "A private space built for comfort and obsession. #renovation #mancave #dreamhouse #barnconversion #dream",
      "author_name": "Aether Studio",
      "author_handle": "@aetherstudio1",
      "created_at": "2026-01-05T21:15:02Z",
      "url": "https://www.tiktok.com/@aetherstudio1/photo/7591989050286804246",
      "like_count": 1100000,
      "bookmark_count": "186556",
      "comment_count": 1992,
      "share_count": 144900,
      "view_count": 11400000,
      "images": [
        {
          "url": "media/tiktok/7591989050286804246/7591989050286804246_01.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7591989050286804246/7591989050286804246_02.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7591989050286804246/7591989050286804246_03.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7591989050286804246/7591989050286804246_04.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7591989050286804246/7591989050286804246_05.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7591989050286804246/7591989050286804246_06.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7591989050286804246/7591989050286804246_07.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7591989050286804246/7591989050286804246_08.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7591989050286804246/7591989050286804246_09.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7591989050286804246/7591989050286804246_10.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7591989050286804246/7591989050286804246_11.jpg",
          "type": "photo"
        }
      ],
      "audio_url": "media/tiktok/7591989050286804246/7591989050286804246.mp3"
    }
  ],
  "2024-11-08": [
    {
      "id": "tt_7434867503165115666",
      "text": "I’m sooo blessed 🥹✨ #grateful #birthdaygirl #gifts #hermes #birkin #unboxing #lovelanguage #princesstreatment #gucci #luxurylifestyle #dubai ",
      "author_name": "Adelinamonsfort",
      "author_handle": "@adelinamonsfort2",
      "created_at": "2024-11-08T11:23:10Z",
      "url": "https://www.tiktok.com/@adelinamonsfort2/photo/7434867503165115666",
      "like_count": 38100,
      "bookmark_count": "3840",
      "comment_count": 310,
      "share_count": 5329,
      "view_count": 685600,
      "images": [
        {
          "url": "media/tiktok/7434867503165115666/7434867503165115666_01.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7434867503165115666/7434867503165115666_02.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7434867503165115666/7434867503165115666_03.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7434867503165115666/7434867503165115666_04.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7434867503165115666/7434867503165115666_05.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7434867503165115666/7434867503165115666_06.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7434867503165115666/7434867503165115666_07.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7434867503165115666/7434867503165115666_08.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7434867503165115666/7434867503165115666_09.jpg",
          "type": "photo"
        }
      ],
      "audio_url": "media/tiktok/7434867503165115666/7434867503165115666.mp3"
    }
  ],
  "2024-11-20": [
    {
      "id": "tt_7439532348774944046",
      "text": "send this to your man, save this for yourself - either way settle in for a niche luxury hot girl gift guide ☕️ #giftguide #holidaygiftguide #eberjey #heavenmayhem #verafied #byredo #tonybianco #guerlain #manieredevoir #miumiu #jwpei #anthropologie #corneliajames #aspinaloflondon #maisonbalzacglassware #fazeek #greenscreen ",
      "author_name": "Sedo",
      "author_handle": "@sedoxo",
      "created_at": "2024-11-21T01:05:10Z",
      "url": "https://www.tiktok.com/@sedoxo/video/7439532348774944046",
      "like_count": 3679,
      "bookmark_count": "2566",
      "comment_count": 78,
      "share_count": 113,
      "view_count": 157700,
      "images": [
        {
          "url": "media/tiktok/7439532348774944046/7439532348774944046_thumb.jpg",
          "type": "video",
          "video_url": "media/tiktok/7439532348774944046/7439532348774944046.mp4"
        }
      ],
      "duration": 431
    }
  ],
  "2023-11-28": [
    {
      "id": "tt_7306673613455904042",
      "text": "Full list of items & prices here:  Dior Loafer - $930 Tekla Bath Towels $15-110 Tom Ford Croc Embossed Wallet $540 Cartier Santos $7,050 Apple Watch Hermes $1,300 Celine “Black Tie” Parfum $280  Louis Vuitton Les Sables Roses $410 Celine Canvas Pouch $490 Bottega Veneta Aviator $440 YSL Toirtoise Shell $460 Aesop Toothpaste $17 Byredo Suede Handsoap $68 Oribe Signature Shampoo $157 Tom Ford Trainers $990 Loewe Messenger Bag $4,100 Baccarat Rouge 540 $120 Loewe Beetroot $230 Hermes Avalon Blanket $1,800 Tom Dixon Tank Whiskey $275 Zwissel Crystal Rocks Glass $40 Rimowa Cabin Plus $1,550 Tom Ford Leather Biker Jacket $6,700 #giftguide #luxury #menswear #christmas #luxurylifestyle #fyp #fypシ ",
      "author_name": "Ben Taylor",
      "author_handle": "@bentaylor_nyc",
      "created_at": "2023-11-29T00:25:39Z",
      "url": "https://www.tiktok.com/@bentaylor_nyc/video/7306673613455904042",
      "like_count": 71700,
      "bookmark_count": "20686",
      "comment_count": 363,
      "share_count": 2904,
      "view_count": 1400000,
      "images": [
        {
          "url": "media/tiktok/7306673613455904042/7306673613455904042_thumb.jpg",
          "type": "video",
          "video_url": "media/tiktok/7306673613455904042/7306673613455904042.mp4"
        }
      ],
      "duration": 96
    }
  ],
  "2025-12-10": [
    {
      "id": "tt_7582110614781218069",
      "text": "Niche luxury for HIM - the thoughtful gift guide that won’t miss! And do we need a part two!? #luxurygifts #giftguide #christmas #giftsforhim #gifting ",
      "author_name": "catspanti",
      "author_handle": "@catspanti",
      "created_at": "2025-12-10T06:21:45Z",
      "url": "https://www.tiktok.com/@catspanti/video/7582110614781218069",
      "like_count": 7403,
      "bookmark_count": "3606",
      "comment_count": 75,
      "share_count": 384,
      "view_count": 181400,
      "images": [
        {
          "url": "media/tiktok/7582110614781218069/7582110614781218069_thumb.jpg",
          "type": "video",
          "video_url": "media/tiktok/7582110614781218069/7582110614781218069.mp4"
        }
      ],
      "duration": 138
    },
    {
      "id": "tt_7580218262915435831",
      "text": "Third Cinema and the Global South #film #globalsouth #thirdworld #cinema #glauberrocha ",
      "author_name": "Machi",
      "author_handle": "@machi7k",
      "created_at": "2025-12-10T16:00:00Z",
      "url": "https://www.tiktok.com/@machi7k/video/7580218262915435831",
      "like_count": 461800,
      "bookmark_count": "87008",
      "comment_count": 1596,
      "share_count": 19300,
      "view_count": 2100000,
      "images": [
        {
          "url": "media/tiktok/7580218262915435831/7580218262915435831_thumb.jpg",
          "type": "video",
          "video_url": "media/tiktok/7580218262915435831/7580218262915435831.mp4"
        }
      ],
      "duration": 85
    }
  ],
  "2025-12-04": [
    {
      "id": "tt_7580222390429371662",
      "text": "#aesthetic #fyp #explore ",
      "author_name": "edgar noe",
      "author_handle": "@edgarolivs",
      "created_at": "2025-12-05T04:14:59Z",
      "url": "https://www.tiktok.com/@edgarolivs/video/7580222390429371662",
      "like_count": 29600,
      "bookmark_count": "4148",
      "comment_count": 69,
      "share_count": 1381,
      "view_count": 218900,
      "images": [
        {
          "url": "media/tiktok/7580222390429371662/7580222390429371662_thumb.jpg",
          "type": "video",
          "video_url": "media/tiktok/7580222390429371662/7580222390429371662.mp4"
        }
      ],
      "duration": 8
    },
    {
      "id": "tt_7580021332704873759",
      "text": "Luxury Gift Guide!  #giftguide #luxurygiftguide #luxuryshopping #luxurygifts #itgirlgiftguide @Louis Vuitton @SAINT LAURENT @The Sleepy Tie @ZIIP @Soft Services @HEAVEN MAYHEM @Barefoot Dreams @Gohar World @Tiffany&Co. ",
      "author_name": "yhasmina.ferrara🍒",
      "author_handle": "@yhasmina.ferrara",
      "created_at": "2025-12-04T15:14:21Z",
      "url": "https://www.tiktok.com/@yhasmina.ferrara/video/7580021332704873759",
      "like_count": 26800,
      "bookmark_count": "16136",
      "comment_count": 310,
      "share_count": 1999,
      "view_count": 580400,
      "images": [
        {
          "url": "media/tiktok/7580021332704873759/7580021332704873759_thumb.jpg",
          "type": "video",
          "video_url": "media/tiktok/7580021332704873759/7580021332704873759.mp4"
        }
      ],
      "duration": 135
    },
    {
      "id": "tt_7580049672258063638",
      "text": "at home :) ",
      "author_name": "davidkoeltgen",
      "author_handle": "@imdavidkoe",
      "created_at": "2025-12-04T17:04:07Z",
      "url": "https://www.tiktok.com/@imdavidkoe/photo/7580049672258063638",
      "like_count": 20400,
      "bookmark_count": "3330",
      "comment_count": 53,
      "share_count": 940,
      "view_count": 139100,
      "images": [
        {
          "url": "media/tiktok/7580049672258063638/7580049672258063638_01.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7580049672258063638/7580049672258063638_02.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7580049672258063638/7580049672258063638_03.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7580049672258063638/7580049672258063638_04.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7580049672258063638/7580049672258063638_05.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7580049672258063638/7580049672258063638_06.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7580049672258063638/7580049672258063638_07.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7580049672258063638/7580049672258063638_08.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7580049672258063638/7580049672258063638_09.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7580049672258063638/7580049672258063638_10.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7580049672258063638/7580049672258063638_11.jpg",
          "type": "photo"
        }
      ],
      "audio_url": "media/tiktok/7580049672258063638/7580049672258063638.mp3"
    }
  ],
  "2025-12-16": [
    {
      "id": "tt_7584344670260497686",
      "text": "#mensfashion #ootd #boyaesthetic #cleanboyaesethetic #pinterestaesthetic ",
      "author_name": "james bradley",
      "author_handle": "@jamesgriffiths_",
      "created_at": "2025-12-16T06:51:09Z",
      "url": "https://www.tiktok.com/@jamesgriffiths_/video/7584344670260497686",
      "like_count": 6335,
      "bookmark_count": "928",
      "comment_count": 16,
      "share_count": 226,
      "view_count": 48100,
      "images": [
        {
          "url": "media/tiktok/7584344670260497686/7584344670260497686_thumb.jpg",
          "type": "video",
          "video_url": "media/tiktok/7584344670260497686/7584344670260497686.mp4"
        }
      ],
      "duration": 7
    }
  ],
  "2025-12-17": [
    {
      "id": "tt_7584963137611336983",
      "text": "#moodboard #abstract #targetaudience ",
      "author_name": "Harvey",
      "author_handle": "@visioniberica",
      "created_at": "2025-12-17T22:50:56Z",
      "url": "https://www.tiktok.com/@visioniberica/video/7584963137611336983",
      "like_count": 168400,
      "bookmark_count": "27591",
      "comment_count": 209,
      "share_count": 10100,
      "view_count": 960800,
      "images": [
        {
          "url": "media/tiktok/7584963137611336983/7584963137611336983_thumb.jpg",
          "type": "video",
          "video_url": "media/tiktok/7584963137611336983/7584963137611336983.mp4"
        }
      ],
      "duration": 9
    }
  ],
  "2025-12-19": [
    {
      "id": "tt_7585669096830799117",
      "text": "spaces for focus, creativity, and growth 🩶 #creativity #creativespaces #designyourlife #productivity #systems ",
      "author_name": "Emily Silver",
      "author_handle": "@emily_silver",
      "created_at": "2025-12-19T20:30:55Z",
      "url": "https://www.tiktok.com/@emily_silver/video/7585669096830799117",
      "like_count": 34600,
      "bookmark_count": "10893",
      "comment_count": 90,
      "share_count": 3288,
      "view_count": 182300,
      "images": [
        {
          "url": "media/tiktok/7585669096830799117/7585669096830799117_thumb.jpg",
          "type": "video",
          "video_url": "media/tiktok/7585669096830799117/7585669096830799117.mp4"
        }
      ],
      "duration": 8
    },
    {
      "id": "tt_7585692632098049302",
      "text": "there is nothing more soulless than modernism and minimalism. #moodboard #targetaudience #niche #minimalism #modernism ",
      "author_name": "2106ers",
      "author_handle": "@2106ers",
      "created_at": "2025-12-19T22:01:43Z",
      "url": "https://www.tiktok.com/@2106ers/video/7585692632098049302",
      "like_count": 34200,
      "bookmark_count": "5327",
      "comment_count": 27,
      "share_count": 1969,
      "view_count": 213400,
      "images": [
        {
          "url": "media/tiktok/7585692632098049302/7585692632098049302_thumb.jpg",
          "type": "video",
          "video_url": "media/tiktok/7585692632098049302/7585692632098049302.mp4"
        }
      ],
      "duration": 5
    }
  ],
  "2025-12-15": [
    {
      "id": "tt_7584203838417095969",
      "text": "#moodboard #fyp #futurenostalgia ",
      "author_name": "￴ ￴ ￴ ￴ ￴",
      "author_handle": "@sun.bleached8",
      "created_at": "2025-12-15T21:44:31Z",
      "url": "https://www.tiktok.com/@sun.bleached8/video/7584203838417095969",
      "like_count": 223000,
      "bookmark_count": "29148",
      "comment_count": 353,
      "share_count": 9365,
      "view_count": 775400,
      "images": [
        {
          "url": "media/tiktok/7584203838417095969/7584203838417095969_thumb.jpg",
          "type": "video",
          "video_url": "media/tiktok/7584203838417095969/7584203838417095969.mp4"
        }
      ],
      "duration": 8
    },
    {
      "id": "tt_7584309550958841118",
      "text": "#outfitinspo #mensfashion #fashion #outfitideasforyou #90s ",
      "author_name": "archivemainline",
      "author_handle": "@archivemainline",
      "created_at": "2025-12-16T04:34:57Z",
      "url": "https://www.tiktok.com/@archivemainline/photo/7584309550958841118",
      "like_count": 35200,
      "bookmark_count": "10818",
      "comment_count": 55,
      "share_count": 1609,
      "view_count": 358800,
      "images": [
        {
          "url": "media/tiktok/7584309550958841118/7584309550958841118_01.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7584309550958841118/7584309550958841118_02.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7584309550958841118/7584309550958841118_03.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7584309550958841118/7584309550958841118_04.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7584309550958841118/7584309550958841118_05.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7584309550958841118/7584309550958841118_06.jpg",
          "type": "photo"
        }
      ],
      "audio_url": "media/tiktok/7584309550958841118/7584309550958841118.mp3"
    },
    {
      "id": "tt_7583954454152629518",
      "text": "Through the fire",
      "author_name": "tristianfilms",
      "author_handle": "@tristianfilms",
      "created_at": "2025-12-15T05:37:30Z",
      "url": "https://www.tiktok.com/@tristianfilms/video/7583954454152629518",
      "like_count": 164300,
      "bookmark_count": "20569",
      "comment_count": 136,
      "share_count": 4764,
      "view_count": 845400,
      "images": [
        {
          "url": "media/tiktok/7583954454152629518/7583954454152629518_thumb.jpg",
          "type": "video",
          "video_url": "media/tiktok/7583954454152629518/7583954454152629518.mp4"
        }
      ],
      "duration": 7
    }
  ],
  "2025-12-21": [
    {
      "id": "tt_7586443588754509078",
      "text": "Jacques Demy’s “The Umbrellas of Cherbourg” is one of the most beautiful films EVER made… and it’s also a great Christmas movie too ❄️ #whattowhatch #cinema #filmtok #theumbrellasofcherbourg #christmasmovies ",
      "author_name": "It’s Just Cinema",
      "author_handle": "@itsjustcinema",
      "created_at": "2025-12-21T22:35:50Z",
      "url": "https://www.tiktok.com/@itsjustcinema/video/7586443588754509078",
      "like_count": 145200,
      "bookmark_count": "65344",
      "comment_count": 517,
      "share_count": 12400,
      "view_count": 1100000,
      "images": [
        {
          "url": "media/tiktok/7586443588754509078/7586443588754509078_thumb.jpg",
          "type": "video",
          "video_url": "media/tiktok/7586443588754509078/7586443588754509078.mp4"
        }
      ],
      "duration": 102
    }
  ],
  "2025-12-14": [
    {
      "id": "tt_7583804683731488030",
      "text": "#goated #foryoupage #scottdisick #moodboardaesthetic #xyzbca ",
      "author_name": "Day Off",
      "author_handle": "@clubdayoff",
      "created_at": "2025-12-14T19:55:46Z",
      "url": "https://www.tiktok.com/@clubdayoff/video/7583804683731488030",
      "like_count": 210600,
      "bookmark_count": "39141",
      "comment_count": 490,
      "share_count": 14800,
      "view_count": 1700000,
      "images": [
        {
          "url": "media/tiktok/7583804683731488030/7583804683731488030_thumb.jpg",
          "type": "video",
          "video_url": "media/tiktok/7583804683731488030/7583804683731488030.mp4"
        }
      ],
      "duration": 18
    },
    {
      "id": "tt_7583622777186340103",
      "text": "ⓘ The path is charted through contemplation, but only action can carry you along it. #masculinearchive #philosophy #edit ",
      "author_name": "MasculineArchive",
      "author_handle": "@masculinearchive",
      "created_at": "2025-12-14T08:09:37Z",
      "url": "https://www.tiktok.com/@masculinearchive/video/7583622777186340103",
      "like_count": 118500,
      "bookmark_count": "24045",
      "comment_count": 211,
      "share_count": 9817,
      "view_count": 775700,
      "images": [
        {
          "url": "media/tiktok/7583622777186340103/7583622777186340103_thumb.jpg",
          "type": "video",
          "video_url": "media/tiktok/7583622777186340103/7583622777186340103.mp4"
        }
      ],
      "duration": 8
    },
    {
      "id": "tt_7583748390379326742",
      "text": "#oldmoney #elegant #lawschool #moodboard ",
      "author_name": "supersecretttt777",
      "author_handle": "@supersecretttt777",
      "created_at": "2025-12-14T16:17:03Z",
      "url": "https://www.tiktok.com/@supersecretttt777/video/7583748390379326742",
      "like_count": 15700,
      "bookmark_count": "3109",
      "comment_count": 26,
      "share_count": 901,
      "view_count": 75600,
      "images": [
        {
          "url": "media/tiktok/7583748390379326742/7583748390379326742_thumb.jpg",
          "type": "video",
          "video_url": "media/tiktok/7583748390379326742/7583748390379326742.mp4"
        }
      ],
      "duration": 15
    },
    {
      "id": "tt_7583727610652364063",
      "text": "#targetaudience #aesthetic #moodboard #niche #swag ",
      "author_name": "Teak and Brass",
      "author_handle": "@teakandbrass",
      "created_at": "2025-12-14T14:56:53Z",
      "url": "https://www.tiktok.com/@teakandbrass/video/7583727610652364063",
      "like_count": 26800,
      "bookmark_count": "3743",
      "comment_count": 21,
      "share_count": 1915,
      "view_count": 136300,
      "images": [
        {
          "url": "media/tiktok/7583727610652364063/7583727610652364063_thumb.jpg",
          "type": "video",
          "video_url": "media/tiktok/7583727610652364063/7583727610652364063.mp4"
        }
      ],
      "duration": 6
    },
    {
      "id": "tt_7583793156433530167",
      "text": ".055 #aesthetic #trace #moodboard #fypp #targetaudience ",
      "author_name": "trace.ltd",
      "author_handle": "@trace.ltd",
      "created_at": "2025-12-14T19:11:23Z",
      "url": "https://www.tiktok.com/@trace.ltd/video/7583793156433530167",
      "like_count": 39700,
      "bookmark_count": "5701",
      "comment_count": 15,
      "share_count": 2522,
      "view_count": 203000,
      "images": [
        {
          "url": "media/tiktok/7583793156433530167/7583793156433530167_thumb.jpg",
          "type": "video",
          "video_url": "media/tiktok/7583793156433530167/7583793156433530167.mp4"
        }
      ],
      "duration": 8
    },
    {
      "id": "tt_7583819503616724237",
      "text": "I miss craftsmanship and curating home with art, textures and patterns. #midcenturymodern #coolhomedecor #homedecor #craftsmanship ",
      "author_name": "pomegranate",
      "author_handle": "@_pomegranate_7",
      "created_at": "2025-12-14T20:53:31Z",
      "url": "https://www.tiktok.com/@_pomegranate_7/video/7583819503616724237",
      "like_count": 2111,
      "bookmark_count": "341",
      "comment_count": 2,
      "share_count": 121,
      "view_count": 14400,
      "images": [
        {
          "url": "media/tiktok/7583819503616724237/7583819503616724237_thumb.jpg",
          "type": "video",
          "video_url": "media/tiktok/7583819503616724237/7583819503616724237.mp4"
        }
      ],
      "duration": 15
    }
  ],
  "2025-12-24": [
    {
      "id": "tt_7587485788330298631",
      "text": "#moodboard #mattdamon #benaffleck #mattfleck #tomhardy #cillianmurphy ",
      "author_name": "🫧",
      "author_handle": "@lockedtapes",
      "created_at": "2025-12-24T18:00:05Z",
      "url": "https://www.tiktok.com/@lockedtapes/video/7587485788330298631",
      "like_count": 54100,
      "bookmark_count": "8435",
      "comment_count": 128,
      "share_count": 2713,
      "view_count": 293700,
      "images": [
        {
          "url": "media/tiktok/7587485788330298631/7587485788330298631_thumb.jpg",
          "type": "video",
          "video_url": "media/tiktok/7587485788330298631/7587485788330298631.mp4"
        }
      ],
      "duration": 12
    }
  ],
  "2025-12-25": [
    {
      "id": "tt_7588002785057082655",
      "text": "TikTok video #7588002785057082655",
      "author_name": "JP",
      "author_handle": "@jplxng",
      "created_at": "2025-12-26T03:26:30Z",
      "url": "https://www.tiktok.com/@jplxng/video/7588002785057082655",
      "like_count": 39800,
      "bookmark_count": "5265",
      "comment_count": 101,
      "share_count": 2182,
      "view_count": 170600,
      "images": [
        {
          "url": "media/tiktok/7588002785057082655/7588002785057082655_thumb.jpg",
          "type": "video",
          "video_url": "media/tiktok/7588002785057082655/7588002785057082655.mp4"
        }
      ],
      "duration": 6
    }
  ],
  "2025-12-05": [
    {
      "id": "tt_7580251218581212446",
      "text": "Solo 💍 #targetaudience #fyp #moodboard #nostalgia #splonz ",
      "author_name": "splonz",
      "author_handle": "@splonz",
      "created_at": "2025-12-05T06:06:40Z",
      "url": "https://www.tiktok.com/@splonz/video/7580251218581212446",
      "like_count": 3064,
      "bookmark_count": "557",
      "comment_count": 20,
      "share_count": 176,
      "view_count": 24400,
      "images": [
        {
          "url": "media/tiktok/7580251218581212446/7580251218581212446_thumb.jpg",
          "type": "video",
          "video_url": "media/tiktok/7580251218581212446/7580251218581212446.mp4"
        }
      ],
      "duration": 14
    }
  ],
  "2025-12-23": [
    {
      "id": "tt_7587142472321600801",
      "text": "#SallyArchives #moodboard #horsewithnoname #style #aestheticvideos ",
      "author_name": "SallyArchives",
      "author_handle": "@sallyarchives",
      "created_at": "2025-12-23T19:47:56Z",
      "url": "https://www.tiktok.com/@sallyarchives/video/7587142472321600801",
      "like_count": 48200,
      "bookmark_count": "6270",
      "comment_count": 38,
      "share_count": 2791,
      "view_count": 264400,
      "images": [
        {
          "url": "media/tiktok/7587142472321600801/7587142472321600801_thumb.jpg",
          "type": "video",
          "video_url": "media/tiktok/7587142472321600801/7587142472321600801.mp4"
        }
      ],
      "duration": 12
    }
  ],
  "2025-12-29": [
    {
      "id": "tt_7589416549295983886",
      "text": "a dream trip 🥾🐟🌲⛺️🍳 ",
      "author_name": "lifevbes",
      "author_handle": "@lifevbess",
      "created_at": "2025-12-29T22:52:57Z",
      "url": "https://www.tiktok.com/@lifevbess/video/7589416549295983886",
      "like_count": 561600,
      "bookmark_count": "58950",
      "comment_count": 1155,
      "share_count": 96800,
      "view_count": 2800000,
      "images": [
        {
          "url": "media/tiktok/7589416549295983886/7589416549295983886_thumb.jpg",
          "type": "video",
          "video_url": "media/tiktok/7589416549295983886/7589416549295983886.mp4"
        }
      ],
      "duration": 8
    }
  ],
  "2023-04-16": [
    {
      "id": "tt_7222813429986331947",
      "text": "to the lego store we go!! ",
      "author_name": "jessica",
      "author_handle": "@cationz",
      "created_at": "2023-04-17T00:45:15Z",
      "url": "https://www.tiktok.com/@cationz/photo/7222813429986331947",
      "like_count": 55100,
      "bookmark_count": "4724",
      "comment_count": 143,
      "share_count": 3032,
      "view_count": 350500,
      "images": [
        {
          "url": "media/tiktok/7222813429986331947/7222813429986331947_01.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7222813429986331947/7222813429986331947_02.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7222813429986331947/7222813429986331947_03.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7222813429986331947/7222813429986331947_04.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7222813429986331947/7222813429986331947_05.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7222813429986331947/7222813429986331947_06.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7222813429986331947/7222813429986331947_07.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7222813429986331947/7222813429986331947_08.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7222813429986331947/7222813429986331947_09.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7222813429986331947/7222813429986331947_10.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7222813429986331947/7222813429986331947_11.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7222813429986331947/7222813429986331947_12.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7222813429986331947/7222813429986331947_13.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7222813429986331947/7222813429986331947_14.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7222813429986331947/7222813429986331947_15.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7222813429986331947/7222813429986331947_16.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7222813429986331947/7222813429986331947_17.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7222813429986331947/7222813429986331947_18.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7222813429986331947/7222813429986331947_19.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7222813429986331947/7222813429986331947_20.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7222813429986331947/7222813429986331947_21.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7222813429986331947/7222813429986331947_22.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7222813429986331947/7222813429986331947_23.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7222813429986331947/7222813429986331947_24.jpg",
          "type": "photo"
        }
      ],
      "audio_url": "media/tiktok/7222813429986331947/7222813429986331947.mp3"
    }
  ],
  "2023-04-22": [
    {
      "id": "tt_7224749003303324955",
      "text": "link in bio (Amazon Essentials - Skin and Hair Products)",
      "author_name": "el",
      "author_handle": "@eldrichyvan",
      "created_at": "2023-04-22T05:56:06Z",
      "url": "https://www.tiktok.com/@eldrichyvan/photo/7224749003303324955",
      "like_count": 59200,
      "bookmark_count": "26864",
      "comment_count": 213,
      "share_count": 806,
      "view_count": 652700,
      "images": [
        {
          "url": "media/tiktok/7224749003303324955/7224749003303324955_01.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7224749003303324955/7224749003303324955_02.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7224749003303324955/7224749003303324955_03.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7224749003303324955/7224749003303324955_04.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7224749003303324955/7224749003303324955_05.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7224749003303324955/7224749003303324955_06.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7224749003303324955/7224749003303324955_07.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7224749003303324955/7224749003303324955_08.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7224749003303324955/7224749003303324955_09.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7224749003303324955/7224749003303324955_10.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7224749003303324955/7224749003303324955_11.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7224749003303324955/7224749003303324955_12.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7224749003303324955/7224749003303324955_13.jpg",
          "type": "photo"
        }
      ],
      "audio_url": "media/tiktok/7224749003303324955/7224749003303324955.mp3"
    }
  ],
  "2023-05-01": [
    {
      "id": "tt_7228372888326278406",
      "text": "My friend told me yesterday: “I don’t want to be 70 yrs old and be a vegetable” 🍅 Two things he can do to avoid that: 1. Resistance training to build muscle 2. Walk every day 3. ⭐️ A daily mobility routine 📌 Save this routine and do it every day if you want to feel and move 10 years younger.",
      "author_name": "Darren Liu | Fitness Coach",
      "author_handle": "@darrenliufitness",
      "created_at": "2023-05-02T00:18:36Z",
      "url": "https://www.tiktok.com/@darrenliufitness/video/7228372888326278406",
      "like_count": 384600,
      "bookmark_count": "301186",
      "comment_count": 1485,
      "share_count": 42800,
      "view_count": 5200000,
      "images": [
        {
          "url": "media/tiktok/7228372888326278406/7228372888326278406_thumb.jpg",
          "type": "video",
          "video_url": "media/tiktok/7228372888326278406/7228372888326278406.mp4"
        }
      ],
      "duration": 90
    }
  ],
  "2023-04-21": [
    {
      "id": "tt_7224473382396661038",
      "text": "This is the difference between like and love ❤️ Clipped from my recent interview with @steven 🙏",
      "author_name": "Jay Shetty",
      "author_handle": "@jayshetty",
      "created_at": "2023-04-21T12:07:07Z",
      "url": "https://www.tiktok.com/@jayshetty/video/7224473382396661038",
      "like_count": 66600,
      "bookmark_count": "13210",
      "comment_count": 163,
      "share_count": 7940,
      "view_count": 694700,
      "images": [
        {
          "url": "media/tiktok/7224473382396661038/7224473382396661038_thumb.jpg",
          "type": "video",
          "video_url": "media/tiktok/7224473382396661038/7224473382396661038.mp4"
        }
      ],
      "duration": 46
    }
  ],
  "2025-12-11": [
    {
      "id": "tt_7582728083753487628",
      "text": "#foryou #moodboard #mountains #hiking #gorpcore ",
      "author_name": "𝓀",
      "author_handle": "@kseniaszn",
      "created_at": "2025-12-11T22:17:48Z",
      "url": "https://www.tiktok.com/@kseniaszn/video/7582728083753487628",
      "like_count": 147500,
      "bookmark_count": "15609",
      "comment_count": 136,
      "share_count": 8433,
      "view_count": 730200,
      "images": [
        {
          "url": "media/tiktok/7582728083753487628/7582728083753487628_thumb.jpg",
          "type": "video",
          "video_url": "media/tiktok/7582728083753487628/7582728083753487628.mp4"
        }
      ],
      "duration": 8
    },
    {
      "id": "tt_7582532019150818581",
      "text": "#positano #oceanaholic #amalfi ",
      "author_name": "🧯",
      "author_handle": "@leehsuhl",
      "created_at": "2025-12-11T09:36:57Z",
      "url": "https://www.tiktok.com/@leehsuhl/video/7582532019150818581",
      "like_count": 2000000,
      "bookmark_count": "255912",
      "comment_count": 1465,
      "share_count": 158800,
      "view_count": 10900000,
      "images": [
        {
          "url": "media/tiktok/7582532019150818581/7582532019150818581_thumb.jpg",
          "type": "video",
          "video_url": "media/tiktok/7582532019150818581/7582532019150818581.mp4"
        }
      ],
      "duration": 13
    }
  ],
  "2025-12-07": [
    {
      "id": "tt_7581277039311801655",
      "text": "How do I explain this feeling ",
      "author_name": "🌙",
      "author_handle": "@solsticewavee",
      "created_at": "2025-12-08T00:27:22Z",
      "url": "https://www.tiktok.com/@solsticewavee/video/7581277039311801655",
      "like_count": 183100,
      "bookmark_count": "23491",
      "comment_count": 206,
      "share_count": 10700,
      "view_count": 933300,
      "images": [
        {
          "url": "media/tiktok/7581277039311801655/7581277039311801655_thumb.jpg",
          "type": "video",
          "video_url": "media/tiktok/7581277039311801655/7581277039311801655.mp4"
        }
      ],
      "duration": 8
    },
    {
      "id": "tt_7581076832565415200",
      "text": "#fyp #music #elegance #edit #rocmarciano ",
      "author_name": "elegance",
      "author_handle": "@elegvnn",
      "created_at": "2025-12-07T11:30:27Z",
      "url": "https://www.tiktok.com/@elegvnn/video/7581076832565415200",
      "like_count": 62500,
      "bookmark_count": "12824",
      "comment_count": 166,
      "share_count": 5084,
      "view_count": 381100,
      "images": [
        {
          "url": "media/tiktok/7581076832565415200/7581076832565415200_thumb.jpg",
          "type": "video",
          "video_url": "media/tiktok/7581076832565415200/7581076832565415200.mp4"
        }
      ],
      "duration": 22
    },
    {
      "id": "tt_7581153587355569463",
      "text": "persian rugs ",
      "author_name": "habeusorpheus",
      "author_handle": "@habeusorpheus",
      "created_at": "2025-12-07T16:28:41Z",
      "url": "https://www.tiktok.com/@habeusorpheus/video/7581153587355569463",
      "like_count": 526900,
      "bookmark_count": "40172",
      "comment_count": 310,
      "share_count": 15400,
      "view_count": 3000000,
      "images": [
        {
          "url": "media/tiktok/7581153587355569463/7581153587355569463_thumb.jpg",
          "type": "video",
          "video_url": "media/tiktok/7581153587355569463/7581153587355569463.mp4"
        }
      ],
      "duration": 6
    },
    {
      "id": "tt_7581187281973710087",
      "text": "#targetaudience#futurehome#niche#moodboard#pinterest ",
      "author_name": "j 🏹📚",
      "author_handle": "@sloanemairi",
      "created_at": "2025-12-07T18:38:42Z",
      "url": "https://www.tiktok.com/@sloanemairi/photo/7581187281973710087",
      "like_count": 283900,
      "bookmark_count": "54330",
      "comment_count": 172,
      "share_count": 13600,
      "view_count": 1200000,
      "images": [
        {
          "url": "media/tiktok/7581187281973710087/7581187281973710087_01.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7581187281973710087/7581187281973710087_02.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7581187281973710087/7581187281973710087_03.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7581187281973710087/7581187281973710087_04.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7581187281973710087/7581187281973710087_05.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7581187281973710087/7581187281973710087_06.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7581187281973710087/7581187281973710087_07.jpg",
          "type": "photo"
        }
      ],
      "audio_url": "media/tiktok/7581187281973710087/7581187281973710087.mp3"
    },
    {
      "id": "tt_7581084071049137430",
      "text": "EVERYDAY HARMONY 🚗🚴🏻‍♀️✨ . . . Product used: @AutoFinesse  #AutoFinesse #Porsche930 #ClassicPorsche #CarCare #Detailing       @Specialized Bicycles @Wahoo Fitness  ",
      "author_name": "Anthony Richelot",
      "author_handle": "@nthnyrchlt",
      "created_at": "2025-12-07T11:58:10Z",
      "url": "https://www.tiktok.com/@nthnyrchlt/video/7581084071049137430",
      "like_count": 190600,
      "bookmark_count": "11574",
      "comment_count": 443,
      "share_count": 20300,
      "view_count": 1600000,
      "images": [
        {
          "url": "media/tiktok/7581084071049137430/7581084071049137430_thumb.jpg",
          "type": "video",
          "video_url": "media/tiktok/7581084071049137430/7581084071049137430.mp4"
        }
      ],
      "duration": 18
    }
  ],
  "2025-12-13": [
    {
      "id": "tt_7583379387110673696",
      "text": "Im back.  #targetaudience #niche #moneytalks #aestheticedits #housemusic ",
      "author_name": "artzume",
      "author_handle": "@artzume",
      "created_at": "2025-12-13T16:25:21Z",
      "url": "https://www.tiktok.com/@artzume/video/7583379387110673696",
      "like_count": 220400,
      "bookmark_count": "34504",
      "comment_count": 281,
      "share_count": 18300,
      "view_count": 1600000,
      "images": [
        {
          "url": "media/tiktok/7583379387110673696/7583379387110673696_thumb.jpg",
          "type": "video",
          "video_url": "media/tiktok/7583379387110673696/7583379387110673696.mp4"
        }
      ],
      "duration": 15
    }
  ],
  "2025-11-23": [
    {
      "id": "tt_7575930593511214358",
      "text": "my current wishlist !  #fyp #fup #fypdong #xybzca #tiktokviral ",
      "author_name": "𝑒𝓂𝒾𝓁𝒾𝒶",
      "author_handle": "@emiliassdiary",
      "created_at": "2025-11-23T14:40:00Z",
      "url": "https://www.tiktok.com/@emiliassdiary/photo/7575930593511214358",
      "like_count": 62400,
      "bookmark_count": "19341",
      "comment_count": 192,
      "share_count": 1106,
      "view_count": 390000,
      "images": [
        {
          "url": "media/tiktok/7575930593511214358/7575930593511214358_01.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7575930593511214358/7575930593511214358_02.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7575930593511214358/7575930593511214358_03.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7575930593511214358/7575930593511214358_04.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7575930593511214358/7575930593511214358_05.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7575930593511214358/7575930593511214358_06.jpg",
          "type": "photo"
        }
      ],
      "audio_url": "media/tiktok/7575930593511214358/7575930593511214358.mp3"
    },
    {
      "id": "tt_7576069513460862221",
      "text": "The beauty in life, will save us. (@حميم) #collage #fyppp #videodiary #hopecore #relatable ",
      "author_name": "love, prosperity",
      "author_handle": "@prosperitylove888",
      "created_at": "2025-11-23T23:39:30Z",
      "url": "https://www.tiktok.com/@prosperitylove888/video/7576069513460862221",
      "like_count": 14900,
      "bookmark_count": "3215",
      "comment_count": 58,
      "share_count": 757,
      "view_count": 79300,
      "images": [
        {
          "url": "media/tiktok/7576069513460862221/7576069513460862221_thumb.jpg",
          "type": "video",
          "video_url": "media/tiktok/7576069513460862221/7576069513460862221.mp4"
        }
      ],
      "duration": 29
    }
  ],
  "2025-11-26": [
    {
      "id": "tt_7577015212046355730",
      "text": "🕴️🏴‍☠️",
      "author_name": "🌴비르🌴",
      "author_handle": "@virbro_",
      "created_at": "2025-11-26T12:48:52Z",
      "url": "https://www.tiktok.com/@virbro_/video/7577015212046355730",
      "like_count": 5600000,
      "bookmark_count": "275893",
      "comment_count": 18400,
      "share_count": 302100,
      "view_count": 56300000,
      "images": [
        {
          "url": "media/tiktok/7577015212046355730/7577015212046355730_thumb.jpg",
          "type": "video",
          "video_url": "media/tiktok/7577015212046355730/7577015212046355730.mp4"
        }
      ],
      "duration": 9
    }
  ],
  "2025-10-17": [
    {
      "id": "tt_7562273607007685899",
      "text": "#contemporaryart ",
      "author_name": "maksymson",
      "author_handle": "@maksymson",
      "created_at": "2025-10-17T19:23:59Z",
      "url": "https://www.tiktok.com/@maksymson/video/7562273607007685899",
      "like_count": 12800,
      "bookmark_count": "1849",
      "comment_count": 26,
      "share_count": 562,
      "view_count": 59500,
      "images": [
        {
          "url": "media/tiktok/7562273607007685899/7562273607007685899_thumb.jpg",
          "type": "video",
          "video_url": "media/tiktok/7562273607007685899/7562273607007685899.mp4"
        }
      ],
      "duration": 7
    }
  ],
  "2025-11-30": [
    {
      "id": "tt_7578378778565545229",
      "text": "Flake - Jack Johnson #music #jackjohnson #targetaudience #surf #xyzbca ",
      "author_name": ".fitsbyjm",
      "author_handle": "@.fitsbyjm",
      "created_at": "2025-11-30T05:00:44Z",
      "url": "https://www.tiktok.com/@.fitsbyjm/video/7578378778565545229",
      "like_count": 138100,
      "bookmark_count": "15164",
      "comment_count": 189,
      "share_count": 5922,
      "view_count": 818200,
      "images": [
        {
          "url": "media/tiktok/7578378778565545229/7578378778565545229_thumb.jpg",
          "type": "video",
          "video_url": "media/tiktok/7578378778565545229/7578378778565545229.mp4"
        }
      ],
      "duration": 25
    }
  ],
  "2025-11-08": [
    {
      "id": "tt_7570573064900021512",
      "text": "a window made for watercolour painting ",
      "author_name": "Eden",
      "author_handle": "@edenvonweiss",
      "created_at": "2025-11-09T04:10:04Z",
      "url": "https://www.tiktok.com/@edenvonweiss/video/7570573064900021512",
      "like_count": 164900,
      "bookmark_count": "17854",
      "comment_count": 522,
      "share_count": 4914,
      "view_count": 1000000,
      "images": [
        {
          "url": "media/tiktok/7570573064900021512/7570573064900021512_thumb.jpg",
          "type": "video",
          "video_url": "media/tiktok/7570573064900021512/7570573064900021512.mp4"
        }
      ],
      "duration": 30
    }
  ],
  "2025-12-03": [
    {
      "id": "tt_7579862183589301534",
      "text": "#college #bedroom #inspo #oldmoney #aesthetic ",
      "author_name": "derf",
      "author_handle": "@derf6969",
      "created_at": "2025-12-04T04:56:57Z",
      "url": "https://www.tiktok.com/@derf6969/photo/7579862183589301534",
      "like_count": 132500,
      "bookmark_count": "26160",
      "comment_count": 138,
      "share_count": 5457,
      "view_count": 718500,
      "images": [
        {
          "url": "media/tiktok/7579862183589301534/7579862183589301534_01.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7579862183589301534/7579862183589301534_02.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7579862183589301534/7579862183589301534_03.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7579862183589301534/7579862183589301534_04.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7579862183589301534/7579862183589301534_05.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7579862183589301534/7579862183589301534_06.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7579862183589301534/7579862183589301534_07.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7579862183589301534/7579862183589301534_08.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7579862183589301534/7579862183589301534_09.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7579862183589301534/7579862183589301534_10.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7579862183589301534/7579862183589301534_11.jpg",
          "type": "photo"
        }
      ],
      "audio_url": "media/tiktok/7579862183589301534/7579862183589301534.mp3"
    },
    {
      "id": "tt_7579807005251013918",
      "text": "@Google is so back",
      "author_name": "Get the Check | Tech + Biz Pod",
      "author_handle": "@getthecheckpod",
      "created_at": "2025-12-04T01:22:43Z",
      "url": "https://www.tiktok.com/@getthecheckpod/video/7579807005251013918",
      "like_count": 123,
      "bookmark_count": "16",
      "comment_count": 0,
      "share_count": 3,
      "view_count": 2316,
      "images": [
        {
          "url": "media/tiktok/7579807005251013918/7579807005251013918_thumb.jpg",
          "type": "video",
          "video_url": "media/tiktok/7579807005251013918/7579807005251013918.mp4"
        }
      ],
      "duration": 80
    }
  ],
  "2025-11-28": [
    {
      "id": "tt_7577957375206886686",
      "text": "Outfits laid out vs. on… #OOTD #pinterestoutfit #sweaterstyle #watchesoftiktok #mensfashion ",
      "author_name": "kian.mccaffrey",
      "author_handle": "@kian.mccaffrey",
      "created_at": "2025-11-29T01:45:17Z",
      "url": "https://www.tiktok.com/@kian.mccaffrey/photo/7577957375206886686",
      "like_count": 43100,
      "bookmark_count": "12936",
      "comment_count": 92,
      "share_count": 1512,
      "view_count": 377800,
      "images": [
        {
          "url": "media/tiktok/7577957375206886686/7577957375206886686_01.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7577957375206886686/7577957375206886686_02.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7577957375206886686/7577957375206886686_03.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7577957375206886686/7577957375206886686_04.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7577957375206886686/7577957375206886686_05.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7577957375206886686/7577957375206886686_06.jpg",
          "type": "photo"
        }
      ],
      "audio_url": "media/tiktok/7577957375206886686/7577957375206886686.mp3"
    }
  ],
  "2025-10-23": [
    {
      "id": "tt_7564453337735695647",
      "text": "it’s all about the details… #menswear #womenswear #stylingtips #minimalstyle #mensaccessories ",
      "author_name": "detailsbyjuju",
      "author_handle": "@detailsbyjuju",
      "created_at": "2025-10-23T16:22:31Z",
      "url": "https://www.tiktok.com/@detailsbyjuju/video/7564453337735695647",
      "like_count": 41500,
      "bookmark_count": "7752",
      "comment_count": 202,
      "share_count": 1875,
      "view_count": 559600,
      "images": [
        {
          "url": "media/tiktok/7564453337735695647/7564453337735695647_thumb.jpg",
          "type": "video",
          "video_url": "media/tiktok/7564453337735695647/7564453337735695647.mp4"
        }
      ],
      "duration": 103
    }
  ],
  "2025-12-01": [
    {
      "id": "tt_7578986204100627732",
      "text": "Coooooooool #internetculture #commentary #videoessay ",
      "author_name": "Matt Prebeg",
      "author_handle": "@mister.tomfoolery",
      "created_at": "2025-12-01T20:17:32Z",
      "url": "https://www.tiktok.com/@mister.tomfoolery/video/7578986204100627732",
      "like_count": 13000,
      "bookmark_count": "3910",
      "comment_count": 162,
      "share_count": 862,
      "view_count": 107000,
      "images": [
        {
          "url": "media/tiktok/7578986204100627732/7578986204100627732_thumb.jpg",
          "type": "video",
          "video_url": "media/tiktok/7578986204100627732/7578986204100627732.mp4"
        }
      ],
      "duration": 155
    }
  ],
  "2025-10-18": [
    {
      "id": "tt_7562570641010969878",
      "text": "y’all already fine now fix ur vibe instead we need more hot energy fr",
      "author_name": "Amelie Kahl",
      "author_handle": "@amyangel666",
      "created_at": "2025-10-18T14:36:35Z",
      "url": "https://www.tiktok.com/@amyangel666/video/7562570641010969878",
      "like_count": 22500,
      "bookmark_count": "5334",
      "comment_count": 109,
      "share_count": 742,
      "view_count": 161300,
      "images": [
        {
          "url": "media/tiktok/7562570641010969878/7562570641010969878_thumb.jpg",
          "type": "video",
          "video_url": "media/tiktok/7562570641010969878/7562570641010969878.mp4"
        }
      ],
      "duration": 50
    }
  ],
  "2025-10-26": [
    {
      "id": "tt_7565699132183039263",
      "text": "what inspired me on pinterest this week as a creative #photographer #artdirection #moodboards #pinterest ",
      "author_name": "connor",
      "author_handle": "@byconnornich",
      "created_at": "2025-10-27T00:56:53Z",
      "url": "https://www.tiktok.com/@byconnornich/photo/7565699132183039263",
      "like_count": 2868,
      "bookmark_count": "810",
      "comment_count": 32,
      "share_count": 36,
      "view_count": 20400,
      "images": [
        {
          "url": "media/tiktok/7565699132183039263/7565699132183039263_01.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7565699132183039263/7565699132183039263_02.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7565699132183039263/7565699132183039263_03.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7565699132183039263/7565699132183039263_04.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7565699132183039263/7565699132183039263_05.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7565699132183039263/7565699132183039263_06.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7565699132183039263/7565699132183039263_07.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7565699132183039263/7565699132183039263_08.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7565699132183039263/7565699132183039263_09.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7565699132183039263/7565699132183039263_10.jpg",
          "type": "photo"
        }
      ],
      "audio_url": "media/tiktok/7565699132183039263/7565699132183039263.mp3"
    },
    {
      "id": "tt_7565662117857201425",
      "text": "At least my photos look like this straight out of camera ✨ #fujifilm #fujifilmxm5 #fujifilmx100vi #photography ",
      "author_name": "Herzawg Fujifilm Photographer",
      "author_handle": "@herzawg",
      "created_at": "2025-10-26T22:34:50Z",
      "url": "https://www.tiktok.com/@herzawg/video/7565662117857201425",
      "like_count": 1500000,
      "bookmark_count": "200953",
      "comment_count": 3150,
      "share_count": 84700,
      "view_count": 15300000,
      "images": [
        {
          "url": "media/tiktok/7565662117857201425/7565662117857201425_thumb.jpg",
          "type": "video",
          "video_url": "media/tiktok/7565662117857201425/7565662117857201425.mp4"
        }
      ],
      "duration": 22
    }
  ],
  "2025-12-09": [
    {
      "id": "tt_7581718602789784853",
      "text": "If you have any of these books on your shelf… Can we be friends? 🥹🖤 #booktok #booktoker #bookrecommendations #classicliterature #readingrecommendations ",
      "author_name": "classicallyclare",
      "author_handle": "@classicallyclare",
      "created_at": "2025-12-09T05:00:39Z",
      "url": "https://www.tiktok.com/@classicallyclare/video/7581718602789784853",
      "like_count": 54100,
      "bookmark_count": "33335",
      "comment_count": 403,
      "share_count": 1189,
      "view_count": 582300,
      "images": [
        {
          "url": "media/tiktok/7581718602789784853/7581718602789784853_thumb.jpg",
          "type": "video",
          "video_url": "media/tiktok/7581718602789784853/7581718602789784853.mp4"
        }
      ],
      "duration": 130
    },
    {
      "id": "tt_7581961131556621623",
      "text": "Japan to Gen Z is India to Millenials #india #japan #genz #aesthetics #millenials ",
      "author_name": "🌬️",
      "author_handle": "@microchipsforbreakfast",
      "created_at": "2025-12-09T20:42:05Z",
      "url": "https://www.tiktok.com/@microchipsforbreakfast/video/7581961131556621623",
      "like_count": 826900,
      "bookmark_count": "80248",
      "comment_count": 4483,
      "share_count": 87300,
      "view_count": 3900000,
      "images": [
        {
          "url": "media/tiktok/7581961131556621623/7581961131556621623_thumb.jpg",
          "type": "video",
          "video_url": "media/tiktok/7581961131556621623/7581961131556621623.mp4"
        }
      ],
      "duration": 160
    }
  ],
  "2025-11-12": [
    {
      "id": "tt_7571982297482808607",
      "text": "Tom Selleck transitions to fall fashion",
      "author_name": "Cody Gould",
      "author_handle": "@cody.gould",
      "created_at": "2025-11-12T23:18:55Z",
      "url": "https://www.tiktok.com/@cody.gould/video/7571982297482808607",
      "like_count": 311400,
      "bookmark_count": "19801",
      "comment_count": 2818,
      "share_count": 16500,
      "view_count": 2500000,
      "images": [
        {
          "url": "media/tiktok/7571982297482808607/7571982297482808607_thumb.jpg",
          "type": "video",
          "video_url": "media/tiktok/7571982297482808607/7571982297482808607.mp4"
        }
      ],
      "duration": 37
    }
  ],
  "2025-11-18": [
    {
      "id": "tt_7574224130397031688",
      "text": "Analog hobbies are dominating the FYP, while tools like @rodeo_app and @Albo App (previously sortd) are trying to get us out in the real world. Might 2026 be lived less online?? #offline #socialmedia #analog #digitaldetox #IRL",
      "author_name": "Carmscrolls",
      "author_handle": "@carmscrolls",
      "created_at": "2025-11-19T00:18:05Z",
      "url": "https://www.tiktok.com/@carmscrolls/video/7574224130397031688",
      "like_count": 144700,
      "bookmark_count": "27511",
      "comment_count": 631,
      "share_count": 6067,
      "view_count": 938600,
      "images": [
        {
          "url": "media/tiktok/7574224130397031688/7574224130397031688_thumb.jpg",
          "type": "video",
          "video_url": "media/tiktok/7574224130397031688/7574224130397031688.mp4"
        }
      ],
      "duration": 91
    },
    {
      "id": "tt_7574125056176016653",
      "text": "#fyp #viral #malibu #summer #surferboy ",
      "author_name": "la1nstyle",
      "author_handle": "@la1nstyle",
      "created_at": "2025-11-18T17:54:38Z",
      "url": "https://www.tiktok.com/@la1nstyle/video/7574125056176016653",
      "like_count": 133300,
      "bookmark_count": "18935",
      "comment_count": 123,
      "share_count": 7716,
      "view_count": 761100,
      "images": [
        {
          "url": "media/tiktok/7574125056176016653/7574125056176016653_thumb.jpg",
          "type": "video",
          "video_url": "media/tiktok/7574125056176016653/7574125056176016653.mp4"
        }
      ],
      "duration": 11
    },
    {
      "id": "tt_7574211829732330765",
      "text": "soundcheck log no. 004 : “industry” • • • • • #dfam • #pulsar23 • #octatrack ",
      "author_name": "Strike Effect",
      "author_handle": "@strikeeffect",
      "created_at": "2025-11-18T23:30:30Z",
      "url": "https://www.tiktok.com/@strikeeffect/video/7574211829732330765",
      "like_count": 9518,
      "bookmark_count": "2483",
      "comment_count": 265,
      "share_count": 430,
      "view_count": 57600,
      "images": [
        {
          "url": "media/tiktok/7574211829732330765/7574211829732330765_thumb.jpg",
          "type": "video",
          "video_url": "media/tiktok/7574211829732330765/7574211829732330765.mp4"
        }
      ],
      "duration": 67
    }
  ],
  "2025-12-12": [
    {
      "id": "tt_7583017372328447262",
      "text": "#edit #icarusreborn ",
      "author_name": "ICARUS REBORN",
      "author_handle": "@icarus.reborn",
      "created_at": "2025-12-12T17:00:48Z",
      "url": "https://www.tiktok.com/@icarus.reborn/video/7583017372328447262",
      "like_count": 191700,
      "bookmark_count": "33440",
      "comment_count": 538,
      "share_count": 8821,
      "view_count": 1000000,
      "images": [
        {
          "url": "media/tiktok/7583017372328447262/7583017372328447262_thumb.jpg",
          "type": "video",
          "video_url": "media/tiktok/7583017372328447262/7583017372328447262.mp4"
        }
      ],
      "duration": 10
    }
  ],
  "2025-11-16": [
    {
      "id": "tt_7573290249728658711",
      "text": "Raw Indian’s Scans",
      "author_name": "lenfantsovage",
      "author_handle": "@lenfantsovage",
      "created_at": "2025-11-16T11:54:07Z",
      "url": "https://www.tiktok.com/@lenfantsovage/video/7573290249728658711",
      "like_count": 5569,
      "bookmark_count": "542",
      "comment_count": 26,
      "share_count": 180,
      "view_count": 52900,
      "images": [
        {
          "url": "media/tiktok/7573290249728658711/7573290249728658711_thumb.jpg",
          "type": "video",
          "video_url": "media/tiktok/7573290249728658711/7573290249728658711.mp4"
        }
      ],
      "duration": 12
    }
  ],
  "2025-11-27": [
    {
      "id": "tt_7577492360032947478",
      "text": "#interior #design #decor #moodboard #fyp ",
      "author_name": "objektarchiv",
      "author_handle": "@objektarchiv",
      "created_at": "2025-11-27T19:40:27Z",
      "url": "https://www.tiktok.com/@objektarchiv/photo/7577492360032947478",
      "like_count": 135000,
      "bookmark_count": "36801",
      "comment_count": 105,
      "share_count": 15200,
      "view_count": 861700,
      "images": [
        {
          "url": "media/tiktok/7577492360032947478/7577492360032947478_01.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7577492360032947478/7577492360032947478_02.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7577492360032947478/7577492360032947478_03.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7577492360032947478/7577492360032947478_04.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7577492360032947478/7577492360032947478_05.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7577492360032947478/7577492360032947478_06.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7577492360032947478/7577492360032947478_07.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7577492360032947478/7577492360032947478_08.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7577492360032947478/7577492360032947478_09.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7577492360032947478/7577492360032947478_10.jpg",
          "type": "photo"
        }
      ],
      "audio_url": "media/tiktok/7577492360032947478/7577492360032947478.mp3"
    }
  ],
  "2025-10-10": [
    {
      "id": "tt_7559464228139142414",
      "text": "Compounding frames. #Lifeonfilm #Filmtok #cinematography ",
      "author_name": "Derrick ⚡️",
      "author_handle": "@derrickmgolden",
      "created_at": "2025-10-10T05:43:16Z",
      "url": "https://www.tiktok.com/@derrickmgolden/video/7559464228139142414",
      "like_count": 492200,
      "bookmark_count": "82560",
      "comment_count": 1076,
      "share_count": 33400,
      "view_count": 2500000,
      "images": [
        {
          "url": "media/tiktok/7559464228139142414/7559464228139142414_thumb.jpg",
          "type": "video",
          "video_url": "media/tiktok/7559464228139142414/7559464228139142414.mp4"
        }
      ],
      "duration": 9
    }
  ],
  "2025-12-02": [
    {
      "id": "tt_7579317077161331999",
      "text": "#rich #cleanboy #luxury #lifestyle ",
      "author_name": "VHM",
      "author_handle": "@vham77",
      "created_at": "2025-12-02T17:41:43Z",
      "url": "https://www.tiktok.com/@vham77/video/7579317077161331999",
      "like_count": 481500,
      "bookmark_count": "69771",
      "comment_count": 934,
      "share_count": 24300,
      "view_count": 3200000,
      "images": [
        {
          "url": "media/tiktok/7579317077161331999/7579317077161331999_thumb.jpg",
          "type": "video",
          "video_url": "media/tiktok/7579317077161331999/7579317077161331999.mp4"
        }
      ],
      "duration": 9
    },
    {
      "id": "tt_7579479891586960648",
      "text": "fourth strike ken! #mensfashion #mensoutfit #menswear #boyfriend #boyoutfit ",
      "author_name": "minigonna",
      "author_handle": "@minigonna_",
      "created_at": "2025-12-03T04:13:07Z",
      "url": "https://www.tiktok.com/@minigonna_/photo/7579479891586960648",
      "like_count": 328600,
      "bookmark_count": "64918",
      "comment_count": 635,
      "share_count": 37400,
      "view_count": 1700000,
      "images": [
        {
          "url": "media/tiktok/7579479891586960648/7579479891586960648_01.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7579479891586960648/7579479891586960648_02.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7579479891586960648/7579479891586960648_03.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7579479891586960648/7579479891586960648_04.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7579479891586960648/7579479891586960648_05.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7579479891586960648/7579479891586960648_06.jpg",
          "type": "photo"
        }
      ],
      "audio_url": "media/tiktok/7579479891586960648/7579479891586960648.mp3"
    }
  ],
  "2025-11-29": [
    {
      "id": "tt_7578253885349907734",
      "text": "#studioapartment #foryoupage #jazz #housedesign #housedecor ",
      "author_name": "𝓙",
      "author_handle": "@fashion_is.life",
      "created_at": "2025-11-29T20:55:33Z",
      "url": "https://www.tiktok.com/@fashion_is.life/video/7578253885349907734",
      "like_count": 122600,
      "bookmark_count": "16179",
      "comment_count": 61,
      "share_count": 8943,
      "view_count": 602000,
      "images": [
        {
          "url": "media/tiktok/7578253885349907734/7578253885349907734_thumb.jpg",
          "type": "video",
          "video_url": "media/tiktok/7578253885349907734/7578253885349907734.mp4"
        }
      ],
      "duration": 9
    },
    {
      "id": "tt_7578266953022721302",
      "text": "Wishlist #grisch #stockholmstil #grischinspo #menswishlist #wishlist ",
      "author_name": "joh_wah",
      "author_handle": "@joh_wah",
      "created_at": "2025-11-29T21:46:16Z",
      "url": "https://www.tiktok.com/@joh_wah/photo/7578266953022721302",
      "like_count": 65700,
      "bookmark_count": "16911",
      "comment_count": 60,
      "share_count": 1777,
      "view_count": 719200,
      "images": [
        {
          "url": "media/tiktok/7578266953022721302/7578266953022721302_01.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7578266953022721302/7578266953022721302_02.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7578266953022721302/7578266953022721302_03.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7578266953022721302/7578266953022721302_04.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7578266953022721302/7578266953022721302_05.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7578266953022721302/7578266953022721302_06.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7578266953022721302/7578266953022721302_07.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7578266953022721302/7578266953022721302_08.jpg",
          "type": "photo"
        }
      ],
      "audio_url": "media/tiktok/7578266953022721302/7578266953022721302.mp3"
    },
    {
      "id": "tt_7578265992233585951",
      "text": "Follow for the names of the agencies Maya worked with #career #careeradvice #recruiting ",
      "author_name": "Get the Check | Tech + Biz Pod",
      "author_handle": "@getthecheckpod",
      "created_at": "2025-11-29T21:42:47Z",
      "url": "https://www.tiktok.com/@getthecheckpod/video/7578265992233585951",
      "like_count": 859,
      "bookmark_count": "397",
      "comment_count": 5,
      "share_count": 51,
      "view_count": 15000,
      "images": [
        {
          "url": "media/tiktok/7578265992233585951/7578265992233585951_thumb.jpg",
          "type": "video",
          "video_url": "media/tiktok/7578265992233585951/7578265992233585951.mp4"
        }
      ],
      "duration": 82
    }
  ],
  "2025-10-30": [
    {
      "id": "tt_7567194081554681101",
      "text": "it’s been a minute ",
      "author_name": "viiiiics",
      "author_handle": "@viiiiics",
      "created_at": "2025-10-31T01:38:14Z",
      "url": "https://www.tiktok.com/@viiiiics/video/7567194081554681101",
      "like_count": 216500,
      "bookmark_count": "28711",
      "comment_count": 225,
      "share_count": 22000,
      "view_count": 1100000,
      "images": [
        {
          "url": "media/tiktok/7567194081554681101/7567194081554681101_thumb.jpg",
          "type": "video",
          "video_url": "media/tiktok/7567194081554681101/7567194081554681101.mp4"
        }
      ],
      "duration": 20
    }
  ],
  "2025-10-25": [
    {
      "id": "tt_7565295595498294542",
      "text": "#fyp #viral #malibu #summer #surferboy",
      "author_name": "la1nstyle",
      "author_handle": "@la1nstyle",
      "created_at": "2025-10-25T22:51:13Z",
      "url": "https://www.tiktok.com/@la1nstyle/video/7565295595498294542",
      "like_count": 57800,
      "bookmark_count": "7651",
      "comment_count": 86,
      "share_count": 3318,
      "view_count": 298400,
      "images": [
        {
          "url": "media/tiktok/7565295595498294542/7565295595498294542_thumb.jpg",
          "type": "video",
          "video_url": "media/tiktok/7565295595498294542/7565295595498294542.mp4"
        }
      ],
      "duration": 13
    }
  ],
  "2025-10-27": [
    {
      "id": "tt_7566063305471560974",
      "text": "Simple rules that make your accessories look intentional. #mensfashiontips #mensfashion #mensjewelry #mensbracelets #mensrings ",
      "author_name": "𝓙𝓑𝓪𝓷𝓭𝓼",
      "author_handle": "@_jbands",
      "created_at": "2025-10-28T00:30:07Z",
      "url": "https://www.tiktok.com/@_jbands/photo/7566063305471560974",
      "like_count": 116300,
      "bookmark_count": "44263",
      "comment_count": 245,
      "share_count": 6400,
      "view_count": 1700000,
      "images": [
        {
          "url": "media/tiktok/7566063305471560974/7566063305471560974_01.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7566063305471560974/7566063305471560974_02.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7566063305471560974/7566063305471560974_03.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7566063305471560974/7566063305471560974_04.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7566063305471560974/7566063305471560974_05.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7566063305471560974/7566063305471560974_06.jpg",
          "type": "photo"
        }
      ],
      "audio_url": "media/tiktok/7566063305471560974/7566063305471560974.mp3"
    }
  ],
  "2025-10-16": [
    {
      "id": "tt_7561866572889902369",
      "text": "#fyp #music #edit #elegance #thealchemist ",
      "author_name": "elegance",
      "author_handle": "@elegvnn",
      "created_at": "2025-10-16T17:04:33Z",
      "url": "https://www.tiktok.com/@elegvnn/video/7561866572889902369",
      "like_count": 27000,
      "bookmark_count": "4109",
      "comment_count": 58,
      "share_count": 1812,
      "view_count": 150100,
      "images": [
        {
          "url": "media/tiktok/7561866572889902369/7561866572889902369_thumb.jpg",
          "type": "video",
          "video_url": "media/tiktok/7561866572889902369/7561866572889902369.mp4"
        }
      ],
      "duration": 13
    }
  ],
  "2025-12-06": [
    {
      "id": "tt_7580721218727218455",
      "text": "#camping#forest#relatablevideos#glamping#fyp ",
      "author_name": "relatablefr07",
      "author_handle": "@relatablefr07",
      "created_at": "2025-12-06T12:30:05Z",
      "url": "https://www.tiktok.com/@relatablefr07/photo/7580721218727218455",
      "like_count": 2900000,
      "bookmark_count": "357854",
      "comment_count": 8260,
      "share_count": 342000,
      "view_count": 17500000,
      "images": [
        {
          "url": "media/tiktok/7580721218727218455/7580721218727218455_01.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7580721218727218455/7580721218727218455_02.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7580721218727218455/7580721218727218455_03.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7580721218727218455/7580721218727218455_04.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7580721218727218455/7580721218727218455_05.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7580721218727218455/7580721218727218455_06.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7580721218727218455/7580721218727218455_07.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7580721218727218455/7580721218727218455_08.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7580721218727218455/7580721218727218455_09.jpg",
          "type": "photo"
        }
      ],
      "audio_url": "media/tiktok/7580721218727218455/7580721218727218455.mp3"
    }
  ],
  "2025-11-22": [
    {
      "id": "tt_7575628751606729998",
      "text": "TikTok video #7575628751606729998",
      "author_name": "zoe",
      "author_handle": "@zoeelizabethh",
      "created_at": "2025-11-22T19:09:11Z",
      "url": "https://www.tiktok.com/@zoeelizabethh/video/7575628751606729998",
      "like_count": 1100000,
      "bookmark_count": "99114",
      "comment_count": 2235,
      "share_count": 70800,
      "view_count": 5600000,
      "images": [
        {
          "url": "media/tiktok/7575628751606729998/7575628751606729998_thumb.jpg",
          "type": "video",
          "video_url": "media/tiktok/7575628751606729998/7575628751606729998.mp4"
        }
      ],
      "duration": 8
    }
  ],
  "2025-10-13": [
    {
      "id": "tt_7560557844198624528",
      "text": "the kind of calm only Kamakura brings, this is why you should visit  #kamakura #kamakurajapan #japan #fyp #shotoniphone ",
      "author_name": "nathanielfong",
      "author_handle": "@nathanielfong",
      "created_at": "2025-10-13T04:26:29Z",
      "url": "https://www.tiktok.com/@nathanielfong/video/7560557844198624528",
      "like_count": 182000,
      "bookmark_count": "37736",
      "comment_count": 327,
      "share_count": 17500,
      "view_count": 884200,
      "images": [
        {
          "url": "media/tiktok/7560557844198624528/7560557844198624528_thumb.jpg",
          "type": "video",
          "video_url": "media/tiktok/7560557844198624528/7560557844198624528.mp4"
        }
      ],
      "duration": 10
    }
  ]
};
