// Auto-generated by fetch_tiktoks.py — do not edit manually.
// Last updated: 2026-08-06T04:15:21Z  |  Total TikToks: 8
// Run: python3 fetch_tiktoks.py --count N
window.TIKTOK_DATES  = {
  "2026-01-03": 2,
  "2026-01-01": 2,
  "2026-01-06": 1,
  "2025-12-30": 1,
  "2025-12-31": 1,
  "2026-01-05": 1
};
window.TIKTOK_VIDEOS = {
  "2026-01-03": [
    {
      "id": "tt_7591098857786805506",
      "text": "03.01 | #moodboard #lifestyle #fyp #itboy #cleanboy ",
      "author_name": "⃟",
      "author_handle": "@cleanlifeguides",
      "created_at": "2026-01-03T11:40:43Z",
      "url": "https://www.tiktok.com/@cleanlifeguides/video/7591098857786805506",
      "like_count": 19700,
      "bookmark_count": "2944",
      "comment_count": 31,
      "share_count": 1173,
      "view_count": 105800,
      "images": [
        {
          "url": "media/tiktok/7591098857786805506/7591098857786805506_thumb.jpg",
          "type": "video",
          "video_url": "media/tiktok/7591098857786805506/7591098857786805506.mp4"
        }
      ],
      "duration": 14
    },
    {
      "id": "tt_7591289647020494102",
      "text": "Tigers symbolize strength, courage, and confidence in many cultures around the world. Flowers often rpresent beauty, growth, and the gentle side of nature. When thinking about tigers and flowers together, they show how nature can be both powerful and soft at the same time. The tigers beauty comes from its bold stripes and fearless presence. The beuauty of flowers comes from their colors, shapes, and calming efect. Both remind us that beauty is not only about appearance, but also meaning and feeling. together, tigers and flowers teach us to respect nature in all its forms. #tiger #moodboard #culture #art #flowers ",
      "author_name": "m",
      "author_handle": "@jcezxv",
      "created_at": "2026-01-04T00:01:04Z",
      "url": "https://www.tiktok.com/@jcezxv/video/7591289647020494102",
      "like_count": 794300,
      "bookmark_count": "110241",
      "comment_count": 1359,
      "share_count": 37700,
      "view_count": 3500000,
      "images": [
        {
          "url": "media/tiktok/7591289647020494102/7591289647020494102_thumb.jpg",
          "type": "video",
          "video_url": "media/tiktok/7591289647020494102/7591289647020494102.mp4"
        }
      ],
      "duration": 11
    }
  ],
  "2026-01-01": [
    {
      "id": "tt_7590530715016645919",
      "text": "No, you’re not messed up—you literally can’t help but be drawn to him.  The tortured pretty-boy aesthetic in media and fashion is a fascinating glimpse into how biology, psychology, societal pressures, media influence and the state of the world impact how we dress, express ourselves and influence what we are drawn to at a given time.  His dichotomous nature—soft yet tough, vulnerable yet defiant—makes him irresistible on every level: visual, emotional, psychological. But what makes him truly hit is his embodiment of a deeply rooted desire: to be authentic without punishment, to feel and display pain without shame (especially among men).  His influence runs deep and wide—even influencing dating culture and beauty trends. But more than that, it underscores the power of marketing and how certain images, style choices and aesthetics can influence mainstream trends and consumer behavior. . . #fashionhistory #fashionhistorian #anakinedit ",
      "author_name": "Trends of the Times",
      "author_handle": "@trendsofthetimes",
      "created_at": "2026-01-01T22:56:16Z",
      "url": "https://www.tiktok.com/@trendsofthetimes/photo/7590530715016645919",
      "like_count": 67200,
      "bookmark_count": "16452",
      "comment_count": 427,
      "share_count": 3418,
      "view_count": 449100,
      "images": [
        {
          "url": "media/tiktok/7590530715016645919/7590530715016645919_01.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7590530715016645919/7590530715016645919_02.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7590530715016645919/7590530715016645919_03.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7590530715016645919/7590530715016645919_04.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7590530715016645919/7590530715016645919_05.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7590530715016645919/7590530715016645919_06.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7590530715016645919/7590530715016645919_07.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7590530715016645919/7590530715016645919_08.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7590530715016645919/7590530715016645919_09.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7590530715016645919/7590530715016645919_10.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7590530715016645919/7590530715016645919_11.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7590530715016645919/7590530715016645919_12.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7590530715016645919/7590530715016645919_13.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7590530715016645919/7590530715016645919_14.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7590530715016645919/7590530715016645919_15.jpg",
          "type": "photo"
        }
      ],
      "audio_url": "media/tiktok/7590530715016645919/7590530715016645919.mp3"
    },
    {
      "id": "tt_7590534882116390175",
      "text": "#coruscant #starwars #jazz #nostalgia #aesthetic ",
      "author_name": "☾",
      "author_handle": "@izvkul",
      "created_at": "2026-01-01T23:12:27Z",
      "url": "https://www.tiktok.com/@izvkul/video/7590534882116390175",
      "like_count": 472100,
      "bookmark_count": "69594",
      "comment_count": 719,
      "share_count": 40300,
      "view_count": 2500000,
      "images": [
        {
          "url": "media/tiktok/7590534882116390175/7590534882116390175_thumb.jpg",
          "type": "video",
          "video_url": "media/tiktok/7590534882116390175/7590534882116390175.mp4"
        }
      ],
      "duration": 8
    }
  ],
  "2026-01-06": [
    {
      "id": "tt_7592269291135831309",
      "text": "TikTok video #7592269291135831309",
      "author_name": "Gabriel",
      "author_handle": "@blessedbythepriest",
      "created_at": "2026-01-06T15:23:30Z",
      "url": "https://www.tiktok.com/@blessedbythepriest/video/7592269291135831309",
      "like_count": 374100,
      "bookmark_count": "37829",
      "comment_count": 571,
      "share_count": 14900,
      "view_count": 2700000,
      "images": [
        {
          "url": "media/tiktok/7592269291135831309/7592269291135831309_thumb.jpg",
          "type": "video",
          "video_url": "media/tiktok/7592269291135831309/7592269291135831309.mp4"
        }
      ],
      "duration": 7
    }
  ],
  "2025-12-30": [
    {
      "id": "tt_7589671680021105942",
      "text": "#outfitinspo #fashiontiktok ",
      "author_name": "Adriano",
      "author_handle": "@adrianoromanini_",
      "created_at": "2025-12-30T15:22:28Z",
      "url": "https://www.tiktok.com/@adrianoromanini_/photo/7589671680021105942",
      "like_count": 60800,
      "bookmark_count": "10747",
      "comment_count": 78,
      "share_count": 2614,
      "view_count": 396200,
      "images": [
        {
          "url": "media/tiktok/7589671680021105942/7589671680021105942_01.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7589671680021105942/7589671680021105942_02.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7589671680021105942/7589671680021105942_03.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7589671680021105942/7589671680021105942_04.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7589671680021105942/7589671680021105942_05.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7589671680021105942/7589671680021105942_06.jpg",
          "type": "photo"
        }
      ],
      "audio_url": "media/tiktok/7589671680021105942/7589671680021105942.mp3"
    }
  ],
  "2025-12-31": [
    {
      "id": "tt_7590112479250812191",
      "text": "Many of these pieces are from our website in bio! #outfitinspo #mensfashion #fashion #outfitideasforyou #90s ",
      "author_name": "archivemainline",
      "author_handle": "@archivemainline",
      "created_at": "2025-12-31T19:53:15Z",
      "url": "https://www.tiktok.com/@archivemainline/photo/7590112479250812191",
      "like_count": 12600,
      "bookmark_count": "2975",
      "comment_count": 11,
      "share_count": 368,
      "view_count": 116300,
      "images": [
        {
          "url": "media/tiktok/7590112479250812191/7590112479250812191_01.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7590112479250812191/7590112479250812191_02.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7590112479250812191/7590112479250812191_03.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7590112479250812191/7590112479250812191_04.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7590112479250812191/7590112479250812191_05.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7590112479250812191/7590112479250812191_06.jpg",
          "type": "photo"
        }
      ],
      "audio_url": "media/tiktok/7590112479250812191/7590112479250812191.mp3"
    }
  ],
  "2026-01-05": [
    {
      "id": "tt_7591989050286804246",
      "text": "A private space built for comfort and obsession. #renovation #mancave #dreamhouse #barnconversion #dream",
      "author_name": "Aether Studio",
      "author_handle": "@aetherstudio1",
      "created_at": "2026-01-05T21:15:02Z",
      "url": "https://www.tiktok.com/@aetherstudio1/photo/7591989050286804246",
      "like_count": 1100000,
      "bookmark_count": "186556",
      "comment_count": 1992,
      "share_count": 144900,
      "view_count": 11400000,
      "images": [
        {
          "url": "media/tiktok/7591989050286804246/7591989050286804246_01.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7591989050286804246/7591989050286804246_02.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7591989050286804246/7591989050286804246_03.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7591989050286804246/7591989050286804246_04.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7591989050286804246/7591989050286804246_05.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7591989050286804246/7591989050286804246_06.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7591989050286804246/7591989050286804246_07.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7591989050286804246/7591989050286804246_08.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7591989050286804246/7591989050286804246_09.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7591989050286804246/7591989050286804246_10.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7591989050286804246/7591989050286804246_11.jpg",
          "type": "photo"
        }
      ],
      "audio_url": "media/tiktok/7591989050286804246/7591989050286804246.mp3"
    }
  ]
};
