// Auto-generated by fetch_tiktoks.py — do not edit manually.
// Last updated: 2026-08-06T04:35:37Z  |  Total TikToks: 28
// Run: python3 fetch_tiktoks.py --count N
window.TIKTOK_DATES  = {
  "2026-01-03": 2,
  "2026-01-01": 3,
  "2026-01-06": 1,
  "2025-12-30": 1,
  "2025-12-31": 1,
  "2026-01-05": 1,
  "2024-11-08": 1,
  "2024-11-20": 1,
  "2023-11-28": 1,
  "2025-12-10": 1,
  "2025-12-04": 1,
  "2025-12-16": 1,
  "2025-12-17": 1,
  "2025-12-19": 2,
  "2025-12-15": 3,
  "2025-12-21": 1,
  "2025-12-14": 1,
  "2025-12-24": 1,
  "2025-12-25": 1,
  "2025-12-05": 1,
  "2025-12-23": 1,
  "2025-12-29": 1
};
window.TIKTOK_VIDEOS = {
  "2026-01-03": [
    {
      "id": "tt_7591098857786805506",
      "text": "03.01 | #moodboard #lifestyle #fyp #itboy #cleanboy ",
      "author_name": "⃟",
      "author_handle": "@cleanlifeguides",
      "created_at": "2026-01-03T11:40:43Z",
      "url": "https://www.tiktok.com/@cleanlifeguides/video/7591098857786805506",
      "like_count": 19700,
      "bookmark_count": "2944",
      "comment_count": 31,
      "share_count": 1173,
      "view_count": 105800,
      "images": [
        {
          "url": "media/tiktok/7591098857786805506/7591098857786805506_thumb.jpg",
          "type": "video",
          "video_url": "media/tiktok/7591098857786805506/7591098857786805506.mp4"
        }
      ],
      "duration": 14
    },
    {
      "id": "tt_7591289647020494102",
      "text": "Tigers symbolize strength, courage, and confidence in many cultures around the world. Flowers often rpresent beauty, growth, and the gentle side of nature. When thinking about tigers and flowers together, they show how nature can be both powerful and soft at the same time. The tigers beauty comes from its bold stripes and fearless presence. The beuauty of flowers comes from their colors, shapes, and calming efect. Both remind us that beauty is not only about appearance, but also meaning and feeling. together, tigers and flowers teach us to respect nature in all its forms. #tiger #moodboard #culture #art #flowers ",
      "author_name": "m",
      "author_handle": "@jcezxv",
      "created_at": "2026-01-04T00:01:04Z",
      "url": "https://www.tiktok.com/@jcezxv/video/7591289647020494102",
      "like_count": 794300,
      "bookmark_count": "110241",
      "comment_count": 1359,
      "share_count": 37700,
      "view_count": 3500000,
      "images": [
        {
          "url": "media/tiktok/7591289647020494102/7591289647020494102_thumb.jpg",
          "type": "video",
          "video_url": "media/tiktok/7591289647020494102/7591289647020494102.mp4"
        }
      ],
      "duration": 11
    }
  ],
  "2026-01-01": [
    {
      "id": "tt_7590530715016645919",
      "text": "No, you’re not messed up—you literally can’t help but be drawn to him.  The tortured pretty-boy aesthetic in media and fashion is a fascinating glimpse into how biology, psychology, societal pressures, media influence and the state of the world impact how we dress, express ourselves and influence what we are drawn to at a given time.  His dichotomous nature—soft yet tough, vulnerable yet defiant—makes him irresistible on every level: visual, emotional, psychological. But what makes him truly hit is his embodiment of a deeply rooted desire: to be authentic without punishment, to feel and display pain without shame (especially among men).  His influence runs deep and wide—even influencing dating culture and beauty trends. But more than that, it underscores the power of marketing and how certain images, style choices and aesthetics can influence mainstream trends and consumer behavior. . . #fashionhistory #fashionhistorian #anakinedit ",
      "author_name": "Trends of the Times",
      "author_handle": "@trendsofthetimes",
      "created_at": "2026-01-01T22:56:16Z",
      "url": "https://www.tiktok.com/@trendsofthetimes/photo/7590530715016645919",
      "like_count": 67200,
      "bookmark_count": "16452",
      "comment_count": 427,
      "share_count": 3418,
      "view_count": 449100,
      "images": [
        {
          "url": "media/tiktok/7590530715016645919/7590530715016645919_01.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7590530715016645919/7590530715016645919_02.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7590530715016645919/7590530715016645919_03.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7590530715016645919/7590530715016645919_04.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7590530715016645919/7590530715016645919_05.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7590530715016645919/7590530715016645919_06.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7590530715016645919/7590530715016645919_07.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7590530715016645919/7590530715016645919_08.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7590530715016645919/7590530715016645919_09.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7590530715016645919/7590530715016645919_10.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7590530715016645919/7590530715016645919_11.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7590530715016645919/7590530715016645919_12.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7590530715016645919/7590530715016645919_13.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7590530715016645919/7590530715016645919_14.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7590530715016645919/7590530715016645919_15.jpg",
          "type": "photo"
        }
      ],
      "audio_url": "media/tiktok/7590530715016645919/7590530715016645919.mp3"
    },
    {
      "id": "tt_7590534882116390175",
      "text": "#coruscant #starwars #jazz #nostalgia #aesthetic ",
      "author_name": "☾",
      "author_handle": "@izvkul",
      "created_at": "2026-01-01T23:12:27Z",
      "url": "https://www.tiktok.com/@izvkul/video/7590534882116390175",
      "like_count": 472100,
      "bookmark_count": "69594",
      "comment_count": 719,
      "share_count": 40300,
      "view_count": 2500000,
      "images": [
        {
          "url": "media/tiktok/7590534882116390175/7590534882116390175_thumb.jpg",
          "type": "video",
          "video_url": "media/tiktok/7590534882116390175/7590534882116390175.mp4"
        }
      ],
      "duration": 8
    },
    {
      "id": "tt_7590443311136050446",
      "text": "The real story of Marty Supreme 🏓 #martysupreme #timotheechalamet #tabletennis ",
      "author_name": "Frank Michael Smith",
      "author_handle": "@frankmichaelsmith",
      "created_at": "2026-01-01T17:17:16Z",
      "url": "https://www.tiktok.com/@frankmichaelsmith/video/7590443311136050446",
      "like_count": 561500,
      "bookmark_count": "32921",
      "comment_count": 626,
      "share_count": 36300,
      "view_count": 5800000,
      "images": [
        {
          "url": "media/tiktok/7590443311136050446/7590443311136050446_thumb.jpg",
          "type": "video",
          "video_url": "media/tiktok/7590443311136050446/7590443311136050446.mp4"
        }
      ],
      "duration": 69
    }
  ],
  "2026-01-06": [
    {
      "id": "tt_7592269291135831309",
      "text": "TikTok video #7592269291135831309",
      "author_name": "Gabriel",
      "author_handle": "@blessedbythepriest",
      "created_at": "2026-01-06T15:23:30Z",
      "url": "https://www.tiktok.com/@blessedbythepriest/video/7592269291135831309",
      "like_count": 374100,
      "bookmark_count": "37829",
      "comment_count": 571,
      "share_count": 14900,
      "view_count": 2700000,
      "images": [
        {
          "url": "media/tiktok/7592269291135831309/7592269291135831309_thumb.jpg",
          "type": "video",
          "video_url": "media/tiktok/7592269291135831309/7592269291135831309.mp4"
        }
      ],
      "duration": 7
    }
  ],
  "2025-12-30": [
    {
      "id": "tt_7589671680021105942",
      "text": "#outfitinspo #fashiontiktok ",
      "author_name": "Adriano",
      "author_handle": "@adrianoromanini_",
      "created_at": "2025-12-30T15:22:28Z",
      "url": "https://www.tiktok.com/@adrianoromanini_/photo/7589671680021105942",
      "like_count": 60800,
      "bookmark_count": "10747",
      "comment_count": 78,
      "share_count": 2614,
      "view_count": 396200,
      "images": [
        {
          "url": "media/tiktok/7589671680021105942/7589671680021105942_01.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7589671680021105942/7589671680021105942_02.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7589671680021105942/7589671680021105942_03.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7589671680021105942/7589671680021105942_04.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7589671680021105942/7589671680021105942_05.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7589671680021105942/7589671680021105942_06.jpg",
          "type": "photo"
        }
      ],
      "audio_url": "media/tiktok/7589671680021105942/7589671680021105942.mp3"
    }
  ],
  "2025-12-31": [
    {
      "id": "tt_7590112479250812191",
      "text": "Many of these pieces are from our website in bio! #outfitinspo #mensfashion #fashion #outfitideasforyou #90s ",
      "author_name": "archivemainline",
      "author_handle": "@archivemainline",
      "created_at": "2025-12-31T19:53:15Z",
      "url": "https://www.tiktok.com/@archivemainline/photo/7590112479250812191",
      "like_count": 12600,
      "bookmark_count": "2975",
      "comment_count": 11,
      "share_count": 368,
      "view_count": 116300,
      "images": [
        {
          "url": "media/tiktok/7590112479250812191/7590112479250812191_01.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7590112479250812191/7590112479250812191_02.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7590112479250812191/7590112479250812191_03.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7590112479250812191/7590112479250812191_04.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7590112479250812191/7590112479250812191_05.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7590112479250812191/7590112479250812191_06.jpg",
          "type": "photo"
        }
      ],
      "audio_url": "media/tiktok/7590112479250812191/7590112479250812191.mp3"
    }
  ],
  "2026-01-05": [
    {
      "id": "tt_7591989050286804246",
      "text": "A private space built for comfort and obsession. #renovation #mancave #dreamhouse #barnconversion #dream",
      "author_name": "Aether Studio",
      "author_handle": "@aetherstudio1",
      "created_at": "2026-01-05T21:15:02Z",
      "url": "https://www.tiktok.com/@aetherstudio1/photo/7591989050286804246",
      "like_count": 1100000,
      "bookmark_count": "186556",
      "comment_count": 1992,
      "share_count": 144900,
      "view_count": 11400000,
      "images": [
        {
          "url": "media/tiktok/7591989050286804246/7591989050286804246_01.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7591989050286804246/7591989050286804246_02.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7591989050286804246/7591989050286804246_03.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7591989050286804246/7591989050286804246_04.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7591989050286804246/7591989050286804246_05.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7591989050286804246/7591989050286804246_06.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7591989050286804246/7591989050286804246_07.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7591989050286804246/7591989050286804246_08.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7591989050286804246/7591989050286804246_09.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7591989050286804246/7591989050286804246_10.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7591989050286804246/7591989050286804246_11.jpg",
          "type": "photo"
        }
      ],
      "audio_url": "media/tiktok/7591989050286804246/7591989050286804246.mp3"
    }
  ],
  "2024-11-08": [
    {
      "id": "tt_7434867503165115666",
      "text": "I’m sooo blessed 🥹✨ #grateful #birthdaygirl #gifts #hermes #birkin #unboxing #lovelanguage #princesstreatment #gucci #luxurylifestyle #dubai ",
      "author_name": "Adelinamonsfort",
      "author_handle": "@adelinamonsfort2",
      "created_at": "2024-11-08T11:23:10Z",
      "url": "https://www.tiktok.com/@adelinamonsfort2/photo/7434867503165115666",
      "like_count": 38100,
      "bookmark_count": "3840",
      "comment_count": 310,
      "share_count": 5329,
      "view_count": 685600,
      "images": [
        {
          "url": "media/tiktok/7434867503165115666/7434867503165115666_01.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7434867503165115666/7434867503165115666_02.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7434867503165115666/7434867503165115666_03.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7434867503165115666/7434867503165115666_04.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7434867503165115666/7434867503165115666_05.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7434867503165115666/7434867503165115666_06.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7434867503165115666/7434867503165115666_07.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7434867503165115666/7434867503165115666_08.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7434867503165115666/7434867503165115666_09.jpg",
          "type": "photo"
        }
      ],
      "audio_url": "media/tiktok/7434867503165115666/7434867503165115666.mp3"
    }
  ],
  "2024-11-20": [
    {
      "id": "tt_7439532348774944046",
      "text": "send this to your man, save this for yourself - either way settle in for a niche luxury hot girl gift guide ☕️ #giftguide #holidaygiftguide #eberjey #heavenmayhem #verafied #byredo #tonybianco #guerlain #manieredevoir #miumiu #jwpei #anthropologie #corneliajames #aspinaloflondon #maisonbalzacglassware #fazeek #greenscreen ",
      "author_name": "Sedo",
      "author_handle": "@sedoxo",
      "created_at": "2024-11-21T01:05:10Z",
      "url": "https://www.tiktok.com/@sedoxo/video/7439532348774944046",
      "like_count": 3679,
      "bookmark_count": "2566",
      "comment_count": 78,
      "share_count": 113,
      "view_count": 157700,
      "images": [
        {
          "url": "media/tiktok/7439532348774944046/7439532348774944046_thumb.jpg",
          "type": "video",
          "video_url": "media/tiktok/7439532348774944046/7439532348774944046.mp4"
        }
      ],
      "duration": 431
    }
  ],
  "2023-11-28": [
    {
      "id": "tt_7306673613455904042",
      "text": "Full list of items & prices here:  Dior Loafer - $930 Tekla Bath Towels $15-110 Tom Ford Croc Embossed Wallet $540 Cartier Santos $7,050 Apple Watch Hermes $1,300 Celine “Black Tie” Parfum $280  Louis Vuitton Les Sables Roses $410 Celine Canvas Pouch $490 Bottega Veneta Aviator $440 YSL Toirtoise Shell $460 Aesop Toothpaste $17 Byredo Suede Handsoap $68 Oribe Signature Shampoo $157 Tom Ford Trainers $990 Loewe Messenger Bag $4,100 Baccarat Rouge 540 $120 Loewe Beetroot $230 Hermes Avalon Blanket $1,800 Tom Dixon Tank Whiskey $275 Zwissel Crystal Rocks Glass $40 Rimowa Cabin Plus $1,550 Tom Ford Leather Biker Jacket $6,700 #giftguide #luxury #menswear #christmas #luxurylifestyle #fyp #fypシ ",
      "author_name": "Ben Taylor",
      "author_handle": "@bentaylor_nyc",
      "created_at": "2023-11-29T00:25:39Z",
      "url": "https://www.tiktok.com/@bentaylor_nyc/video/7306673613455904042",
      "like_count": 71700,
      "bookmark_count": "20686",
      "comment_count": 363,
      "share_count": 2904,
      "view_count": 1400000,
      "images": [
        {
          "url": "media/tiktok/7306673613455904042/7306673613455904042_thumb.jpg",
          "type": "video",
          "video_url": "media/tiktok/7306673613455904042/7306673613455904042.mp4"
        }
      ],
      "duration": 96
    }
  ],
  "2025-12-10": [
    {
      "id": "tt_7582110614781218069",
      "text": "Niche luxury for HIM - the thoughtful gift guide that won’t miss! And do we need a part two!? #luxurygifts #giftguide #christmas #giftsforhim #gifting ",
      "author_name": "catspanti",
      "author_handle": "@catspanti",
      "created_at": "2025-12-10T06:21:45Z",
      "url": "https://www.tiktok.com/@catspanti/video/7582110614781218069",
      "like_count": 7403,
      "bookmark_count": "3606",
      "comment_count": 75,
      "share_count": 384,
      "view_count": 181400,
      "images": [
        {
          "url": "media/tiktok/7582110614781218069/7582110614781218069_thumb.jpg",
          "type": "video",
          "video_url": "media/tiktok/7582110614781218069/7582110614781218069.mp4"
        }
      ],
      "duration": 138
    }
  ],
  "2025-12-04": [
    {
      "id": "tt_7580222390429371662",
      "text": "#aesthetic #fyp #explore ",
      "author_name": "edgar noe",
      "author_handle": "@edgarolivs",
      "created_at": "2025-12-05T04:14:59Z",
      "url": "https://www.tiktok.com/@edgarolivs/video/7580222390429371662",
      "like_count": 29600,
      "bookmark_count": "4148",
      "comment_count": 69,
      "share_count": 1381,
      "view_count": 218900,
      "images": [
        {
          "url": "media/tiktok/7580222390429371662/7580222390429371662_thumb.jpg",
          "type": "video",
          "video_url": "media/tiktok/7580222390429371662/7580222390429371662.mp4"
        }
      ],
      "duration": 8
    }
  ],
  "2025-12-16": [
    {
      "id": "tt_7584344670260497686",
      "text": "#mensfashion #ootd #boyaesthetic #cleanboyaesethetic #pinterestaesthetic ",
      "author_name": "james bradley",
      "author_handle": "@jamesgriffiths_",
      "created_at": "2025-12-16T06:51:09Z",
      "url": "https://www.tiktok.com/@jamesgriffiths_/video/7584344670260497686",
      "like_count": 6335,
      "bookmark_count": "928",
      "comment_count": 16,
      "share_count": 226,
      "view_count": 48100,
      "images": [
        {
          "url": "media/tiktok/7584344670260497686/7584344670260497686_thumb.jpg",
          "type": "video",
          "video_url": "media/tiktok/7584344670260497686/7584344670260497686.mp4"
        }
      ],
      "duration": 7
    }
  ],
  "2025-12-17": [
    {
      "id": "tt_7584963137611336983",
      "text": "#moodboard #abstract #targetaudience ",
      "author_name": "Harvey",
      "author_handle": "@visioniberica",
      "created_at": "2025-12-17T22:50:56Z",
      "url": "https://www.tiktok.com/@visioniberica/video/7584963137611336983",
      "like_count": 168400,
      "bookmark_count": "27591",
      "comment_count": 209,
      "share_count": 10100,
      "view_count": 960800,
      "images": [
        {
          "url": "media/tiktok/7584963137611336983/7584963137611336983_thumb.jpg",
          "type": "video",
          "video_url": "media/tiktok/7584963137611336983/7584963137611336983.mp4"
        }
      ],
      "duration": 9
    }
  ],
  "2025-12-19": [
    {
      "id": "tt_7585669096830799117",
      "text": "spaces for focus, creativity, and growth 🩶 #creativity #creativespaces #designyourlife #productivity #systems ",
      "author_name": "Emily Silver",
      "author_handle": "@emily_silver",
      "created_at": "2025-12-19T20:30:55Z",
      "url": "https://www.tiktok.com/@emily_silver/video/7585669096830799117",
      "like_count": 34600,
      "bookmark_count": "10893",
      "comment_count": 90,
      "share_count": 3288,
      "view_count": 182300,
      "images": [
        {
          "url": "media/tiktok/7585669096830799117/7585669096830799117_thumb.jpg",
          "type": "video",
          "video_url": "media/tiktok/7585669096830799117/7585669096830799117.mp4"
        }
      ],
      "duration": 8
    },
    {
      "id": "tt_7585692632098049302",
      "text": "there is nothing more soulless than modernism and minimalism. #moodboard #targetaudience #niche #minimalism #modernism ",
      "author_name": "2106ers",
      "author_handle": "@2106ers",
      "created_at": "2025-12-19T22:01:43Z",
      "url": "https://www.tiktok.com/@2106ers/video/7585692632098049302",
      "like_count": 34200,
      "bookmark_count": "5327",
      "comment_count": 27,
      "share_count": 1969,
      "view_count": 213400,
      "images": [
        {
          "url": "media/tiktok/7585692632098049302/7585692632098049302_thumb.jpg",
          "type": "video",
          "video_url": "media/tiktok/7585692632098049302/7585692632098049302.mp4"
        }
      ],
      "duration": 5
    }
  ],
  "2025-12-15": [
    {
      "id": "tt_7584203838417095969",
      "text": "#moodboard #fyp #futurenostalgia ",
      "author_name": "￴ ￴ ￴ ￴ ￴",
      "author_handle": "@sun.bleached8",
      "created_at": "2025-12-15T21:44:31Z",
      "url": "https://www.tiktok.com/@sun.bleached8/video/7584203838417095969",
      "like_count": 223000,
      "bookmark_count": "29148",
      "comment_count": 353,
      "share_count": 9365,
      "view_count": 775400,
      "images": [
        {
          "url": "media/tiktok/7584203838417095969/7584203838417095969_thumb.jpg",
          "type": "video",
          "video_url": "media/tiktok/7584203838417095969/7584203838417095969.mp4"
        }
      ],
      "duration": 8
    },
    {
      "id": "tt_7584309550958841118",
      "text": "#outfitinspo #mensfashion #fashion #outfitideasforyou #90s ",
      "author_name": "archivemainline",
      "author_handle": "@archivemainline",
      "created_at": "2025-12-16T04:34:57Z",
      "url": "https://www.tiktok.com/@archivemainline/photo/7584309550958841118",
      "like_count": 35200,
      "bookmark_count": "10818",
      "comment_count": 55,
      "share_count": 1609,
      "view_count": 358800,
      "images": [
        {
          "url": "media/tiktok/7584309550958841118/7584309550958841118_01.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7584309550958841118/7584309550958841118_02.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7584309550958841118/7584309550958841118_03.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7584309550958841118/7584309550958841118_04.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7584309550958841118/7584309550958841118_05.jpg",
          "type": "photo"
        },
        {
          "url": "media/tiktok/7584309550958841118/7584309550958841118_06.jpg",
          "type": "photo"
        }
      ],
      "audio_url": "media/tiktok/7584309550958841118/7584309550958841118.mp3"
    },
    {
      "id": "tt_7583954454152629518",
      "text": "Through the fire",
      "author_name": "tristianfilms",
      "author_handle": "@tristianfilms",
      "created_at": "2025-12-15T05:37:30Z",
      "url": "https://www.tiktok.com/@tristianfilms/video/7583954454152629518",
      "like_count": 164300,
      "bookmark_count": "20569",
      "comment_count": 136,
      "share_count": 4764,
      "view_count": 845400,
      "images": [
        {
          "url": "media/tiktok/7583954454152629518/7583954454152629518_thumb.jpg",
          "type": "video",
          "video_url": "media/tiktok/7583954454152629518/7583954454152629518.mp4"
        }
      ],
      "duration": 7
    }
  ],
  "2025-12-21": [
    {
      "id": "tt_7586443588754509078",
      "text": "Jacques Demy’s “The Umbrellas of Cherbourg” is one of the most beautiful films EVER made… and it’s also a great Christmas movie too ❄️ #whattowhatch #cinema #filmtok #theumbrellasofcherbourg #christmasmovies ",
      "author_name": "It’s Just Cinema",
      "author_handle": "@itsjustcinema",
      "created_at": "2025-12-21T22:35:50Z",
      "url": "https://www.tiktok.com/@itsjustcinema/video/7586443588754509078",
      "like_count": 145200,
      "bookmark_count": "65344",
      "comment_count": 517,
      "share_count": 12400,
      "view_count": 1100000,
      "images": [
        {
          "url": "media/tiktok/7586443588754509078/7586443588754509078_thumb.jpg",
          "type": "video",
          "video_url": "media/tiktok/7586443588754509078/7586443588754509078.mp4"
        }
      ],
      "duration": 102
    }
  ],
  "2025-12-14": [
    {
      "id": "tt_7583804683731488030",
      "text": "#goated #foryoupage #scottdisick #moodboardaesthetic #xyzbca ",
      "author_name": "Day Off",
      "author_handle": "@clubdayoff",
      "created_at": "2025-12-14T19:55:46Z",
      "url": "https://www.tiktok.com/@clubdayoff/video/7583804683731488030",
      "like_count": 210600,
      "bookmark_count": "39141",
      "comment_count": 490,
      "share_count": 14800,
      "view_count": 1700000,
      "images": [
        {
          "url": "media/tiktok/7583804683731488030/7583804683731488030_thumb.jpg",
          "type": "video",
          "video_url": "media/tiktok/7583804683731488030/7583804683731488030.mp4"
        }
      ],
      "duration": 18
    }
  ],
  "2025-12-24": [
    {
      "id": "tt_7587485788330298631",
      "text": "#moodboard #mattdamon #benaffleck #mattfleck #tomhardy #cillianmurphy ",
      "author_name": "🫧",
      "author_handle": "@lockedtapes",
      "created_at": "2025-12-24T18:00:05Z",
      "url": "https://www.tiktok.com/@lockedtapes/video/7587485788330298631",
      "like_count": 54100,
      "bookmark_count": "8435",
      "comment_count": 128,
      "share_count": 2713,
      "view_count": 293700,
      "images": [
        {
          "url": "media/tiktok/7587485788330298631/7587485788330298631_thumb.jpg",
          "type": "video",
          "video_url": "media/tiktok/7587485788330298631/7587485788330298631.mp4"
        }
      ],
      "duration": 12
    }
  ],
  "2025-12-25": [
    {
      "id": "tt_7588002785057082655",
      "text": "TikTok video #7588002785057082655",
      "author_name": "JP",
      "author_handle": "@jplxng",
      "created_at": "2025-12-26T03:26:30Z",
      "url": "https://www.tiktok.com/@jplxng/video/7588002785057082655",
      "like_count": 39800,
      "bookmark_count": "5265",
      "comment_count": 101,
      "share_count": 2182,
      "view_count": 170600,
      "images": [
        {
          "url": "media/tiktok/7588002785057082655/7588002785057082655_thumb.jpg",
          "type": "video",
          "video_url": "media/tiktok/7588002785057082655/7588002785057082655.mp4"
        }
      ],
      "duration": 6
    }
  ],
  "2025-12-05": [
    {
      "id": "tt_7580251218581212446",
      "text": "Solo 💍 #targetaudience #fyp #moodboard #nostalgia #splonz ",
      "author_name": "splonz",
      "author_handle": "@splonz",
      "created_at": "2025-12-05T06:06:40Z",
      "url": "https://www.tiktok.com/@splonz/video/7580251218581212446",
      "like_count": 3064,
      "bookmark_count": "557",
      "comment_count": 20,
      "share_count": 176,
      "view_count": 24400,
      "images": [
        {
          "url": "media/tiktok/7580251218581212446/7580251218581212446_thumb.jpg",
          "type": "video",
          "video_url": "media/tiktok/7580251218581212446/7580251218581212446.mp4"
        }
      ],
      "duration": 14
    }
  ],
  "2025-12-23": [
    {
      "id": "tt_7587142472321600801",
      "text": "#SallyArchives #moodboard #horsewithnoname #style #aestheticvideos ",
      "author_name": "SallyArchives",
      "author_handle": "@sallyarchives",
      "created_at": "2025-12-23T19:47:56Z",
      "url": "https://www.tiktok.com/@sallyarchives/video/7587142472321600801",
      "like_count": 48200,
      "bookmark_count": "6270",
      "comment_count": 38,
      "share_count": 2791,
      "view_count": 264400,
      "images": [
        {
          "url": "media/tiktok/7587142472321600801/7587142472321600801_thumb.jpg",
          "type": "video",
          "video_url": "media/tiktok/7587142472321600801/7587142472321600801.mp4"
        }
      ],
      "duration": 12
    }
  ],
  "2025-12-29": [
    {
      "id": "tt_7589416549295983886",
      "text": "a dream trip 🥾🐟🌲⛺️🍳 ",
      "author_name": "lifevbes",
      "author_handle": "@lifevbess",
      "created_at": "2025-12-29T22:52:57Z",
      "url": "https://www.tiktok.com/@lifevbess/video/7589416549295983886",
      "like_count": 561600,
      "bookmark_count": "58950",
      "comment_count": 1155,
      "share_count": 96800,
      "view_count": 2800000,
      "images": [
        {
          "url": "media/tiktok/7589416549295983886/7589416549295983886_thumb.jpg",
          "type": "video",
          "video_url": "media/tiktok/7589416549295983886/7589416549295983886.mp4"
        }
      ],
      "duration": 8
    }
  ]
};
